### ISSUE TITLE
Edit WebDAV Connection

### ISSUE THREAD

**Issue by fishcharlie** [cryptomator/ios#101]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Edit WebDAV Connection

### Motivation

There doesn't seem to be anyway to edit the WebDAV connection details.

### Considered Alternatives

Removing the WebDAV server and re-adding. However, that is a pretty bad workaround.

### Anything else?

Ported over from https://github.com/cryptomator/cryptomator-ios/issues/167.

**Comment by phil1995** [comment]
This has been implemented over a year ago.
