### ISSUE TITLE
Prompt authentication process if files are shared to locked vault via files app

### ISSUE THREAD

**Issue by StanoRiga** [cryptomator/ios#111]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Show authentication UI if you try to share something into a locked vault via save to files process

### System Setup

- iOS: 15.1.1
- Cryptomator: 2.0.0. (609)

### Cloud Type

iCloud Drive, Dropbox, Google Drive, OneDrive, WebDAV, Other File Provider

### Steps to Reproduce

1. Lock all vaults or at least the one you are trying the following 
2. go to photos (or any other app that allows to start the process "share -> save to files")
3. share a file, select "save to files"
4. select a locked vault

### Expected Behavior

The process for authentication starts and the UI for password/faceID is shown
(just like it is if you click on a locked vault in files app (without sharing something)

### Actual Behavior

Authentication does not start. The small arrow right to the vaults name is swithcing to indicate there are subfolders, but you can not open the vault without leaving the share process.
You have to leave the process, unlock the vault and start the share process again with an unlocked vault.

### Reproducibility

Always

### Anything else?

https://community.cryptomator.org/t/save-to-files-share-sheet-action-doesn-t-present-prompt-to-unlock-vault/8976
(includes video)

**Comment by StanoRiga** [comment]
see linked community board. Answer from @tobihagemann:

> Unfortunately, that’s not possible and we’re restricted by the technical capabilities of iOS (or the Files app). Even though it’s not a solution, there is a feature request here https://github.com/cryptomator/ios/issues/73 that could be a workaround someday.

(opened the github issue while he was answering the question in the board)

**Comment by tobihagemann** [comment]
[Quoting jmreekes on Cryptomator Community:](https://community.cryptomator.org/t/save-to-files-share-sheet-action-doesn-t-present-prompt-to-unlock-vault/8976/5?u=tobihagemann)

> I remembered Boxcryptor having this [same issue](https://www.boxcryptor.com/en/blog/post/files-protection-ios/) with their Files Protection function. They use system notifications to alert that the vault needs to be unlocked and the notification takes the user to the Boxcryptor app to unlock the vault and the user can then use the back button or swipe gesture to go back to the original app.
> 
> This could be another possibility for making it easier to get around having to keep vaults unlocked all the time.

**Comment by tobihagemann** [comment]
This has been fixed in iOS 16. 🎉
