### ISSUE TITLE
Penalty of the background URLSession in the Main App

### ISSUE THREAD

**Issue by phil1995** [cryptomator/ios#12]
Although Apple states in the [documentation](https://developer.apple.com/documentation/foundation/url_loading_system/downloading_files_in_the_background) that the delay of the background `URLSession` is set to 0 when the app comes to the foreground:

> The delay is reset to 0 whenever the user brings your app to the foreground. It also resets if the delay period elapses without the system resuming or relaunching your app.

The background `URLSession` in the main app in the foreground is penalized. See also: [Apple Developer Forum](https://developer.apple.com/forums/thread/124450), [ownCloud Issue](https://github.com/owncloud/ios-sdk/issues/46).

This does _not_ affect the FileProvider.
Therefore it is probably necessary to use a foreground `URLSession` for the login to a CloudProvider account & the installation process of a Vault to reduce the delay. The authentication at GoogleDrive (via `AppAuth`) is also done with the default shared `URLSession` (foreground `URLSession`).

**Comment by tobihagemann** [comment]
Fixed in ff3f5348d56191e405c13fc2f6e6edc71edae94a and 89df416d6d139dca13fdbc4dfd4b4c0359f1399f
