### ISSUE TITLE
Last file remains open when exiting then returning to Files app

### ISSUE THREAD

**Issue by plasticrhinox** [cryptomator/ios#135]
### Please agree to the following

- [x] I have searched [existing issues](https://github.com/cryptomator/cryptomator/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/cryptomator/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

In the File app i enable Cryptomator only when i use it. Otherwise i switch it off in the Files app. In this instance i opened an image file in Files. Jumped to another app. Returned to Files. Closed the image file and disabled Cryptomator. Closed the Files app. Upon reopening the Files app i was presented with the open image file, even when Cryptomator was disabled in Files.

### What software is involved?

- Operating System: iOS 15.2
- Cryptomator: 2.0
- Vault stored in Google Drive

### Steps to Reproduce

1. Cryptomator 2.0 enabled in iOS Files app using a vault in Google Drive.
2. Browse Cryptomator files and open an image.
3. While image is open minimise Cryptomator or switch to another app.
4. Return to Cryptomator, close image, disable Cryptomator in Files (click 3 dots in top-right, click Edit, disable Cryptomator).
5. Close Files app.
6. Return to Files app.
7. Previously opened image file is still open and front and centre, even though Cryptomator is disabled.

### Expected Behavior

Image should not be loaded. It should be locked away in the vault.

### Actual Behavior

Even though Cryptomator is disabled in Files the image contained in the vault is still loaded.

### Reproducibility

Only once

**Comment by tobihagemann** [comment]
Enabling/disabling Cryptomator in the Files app doesn't unlock/lock the vault. Sounds like a nice idea but that's just not how the Files app works and wo don't have control over enabling/disabling it.

If you'd like to lock the vault, you have to open the Cryptomator app. Either tap on the open lock icon (in the vaults list) or tap "Lock Now" in the vault detail screen.

**Comment by plasticrhinox** [comment]
Ok thanks for clarifying
