### ISSUE TITLE
Problem opening excel files from ios files app 

### ISSUE THREAD

**Issue by s73fan** [cryptomator/ios#136]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Changes made to excel files after opening the file from ios files app are not saved. 

### System Setup

- iOS: 15.2
- Cryptomator: 2.0.2 (747)
- Office 2.56

### Cloud Type

Google Drive

### Steps to Reproduce

# not working way
1. open ios files app
2. browse to excel file within a Cryptomator container
3. click the excel file (will be opened in office app)
4. Modify the excel file in any way
5. Close the excel file
6. Reopen the excel file in any way (you can use the same device or another one)
7. See that the changes made under 4. are lost

# working way
1. open office app
2. Choose „files app“ within the office app
3. Browse to an excel file within the Cryptomator continer
4. Open the excel file within the office app
5. Modify the excel file in any way
6. Close the excel file
7. Reopen the excel file in any way (you can use the same device or another one)
8. See that the changes made under 5. are correctly stored

### Expected Behavior

Both ways should lead to a persitant change of the excel file

### Actual Behavior

Only opening the file within the office app leads to a stored change

### Reproducibility

Always

**Comment by tobihagemann** [comment]
Thank you for reporting this issue! It might be related to #134. A fix for it is already on the way with version 2.0.3. It's currently waiting for review by Apple.

**Comment by s73fan** [comment]
Yes right. I just got the 2.0.3 update. Now it works fine 👍 Thanks, Stefan
