### ISSUE TITLE
Unable to buy in-app purchase (SKErrorDomain Error 0)

### ISSUE THREAD

**Issue by BasePointer** [cryptomator/ios#146]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Trying to upgrade from Cryptomator 1.x and 30-day trial both result in an error code

### System Setup

- iOS: [15.2]
- Cryptomator: [2.0.4]

### Steps to Reproduce

- I open the Cryptomator 2 app
- I open the settings using the gear symbol in the top left
- I click on _"Unlock Full Version"_ (translation might be vary)
- I click on _"Upgrade from Version 1.x"_ (translation might be vary)
- I click on _"Free Upgrade"_ (translation might be vary)
- I confirm the in app purchase via the app store by tapping the power button twice
- In app purchase says _"payment is being confirmed"_ -> _"done"_ (translation might be vary)

### Expected Behavior

I expect the app to acknowledge the in app purchase and upgrade to the full version.

### Actual Behavior

I get an error _"Error: The process could not be completed. (SKErrorDomain-Error 0.)"_ (translation might be vary)

### Reproducibility

Always

### Relevant Log Output

```shell
2022/01/03 22:12:10:754  Purchase of org.cryptomator.ios.iap.free_upgrade failed with error: Error Domain=SKErrorDomain Code=0 "(null)"
2022/01/03 22:12:10:768  Error: Error Domain=SKErrorDomain Code=0 "(null)"
2022/01/03 22:13:07:874  Removing all unused FileProviderDomains failed with error: Error Domain=NSPOSIXErrorDomain Code=22 "Default domain cannot be removed" UserInfo={NSDescription=Default domain cannot be removed}
2022/01/03 22:13:19:799  Purchase of org.cryptomator.ios.iap.free_upgrade failed with error: Error Domain=SKErrorDomain Code=0 "(null)"
2022/01/03 22:13:19:818  Error: Error Domain=SKErrorDomain Code=0 "(null)"
2022/01/03 22:16:36:109  Purchase of org.cryptomator.ios.iap.free_upgrade failed with error: Error Domain=SKErrorDomain Code=0 "(null)"
2022/01/03 22:16:36:127  Error: Error Domain=SKErrorDomain Code=0 "(null)"
2022/01/03 22:22:57:227  Buy product: org.cryptomator.ios.iap.free_upgrade
2022/01/03 22:23:06:734  Purchase of org.cryptomator.ios.iap.free_upgrade failed with error: Error Domain=SKErrorDomain Code=0 "(null)"
2022/01/03 22:23:06:735  Removed org.cryptomator.ios.iap.free_upgrade from the payment queue
2022/01/03 22:23:06:749  Error: Error Domain=SKErrorDomain Code=0 "(null)"
2022/01/03 22:23:10:445  Buy product: org.cryptomator.ios.iap.30_day_trial
2022/01/03 22:23:18:347  Purchase of org.cryptomator.ios.iap.30_day_trial failed with error: Error Domain=SKErrorDomain Code=0 "(null)"
2022/01/03 22:23:18:348  Removed org.cryptomator.ios.iap.30_day_trial from the payment queue
2022/01/03 22:23:18:355  Error: Error Domain=SKErrorDomain Code=0 "(null)"
```

### Anything else?

The same issue arises when trying to opt for the 30-day trial. I was beta testing the testflight version if that is of interest. The paid upgrade does work.

**Comment by HerbertNielsen** [comment]
I had the same issue when my free trials ended. After deinstalling and reinstalling Crymptomator worked fine.
