### ISSUE TITLE
Password known to work on Windows rejected by iOS app

### ISSUE THREAD

**Issue by SNHPhSvrdB** [cryptomator/ios#151]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/cryptomator/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/cryptomator/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

I cannot open a OneDrive vault on Cryptomator 2

### What software is involved?

- Operating System: iOS 15.2
- Cryptomator: 2.0.4
- …

### Steps to Reproduce

1. Opened OneDrive Vault
2. Entered password
3. Shaking animation

### Expected Behavior

The OneDrive folder should open

### Actual Behavior

When I tried to open the OneDrive vault, I got a shaking animation. I know the password is correct as I can open it on my Windows 10 computer. I’ve made five separate vaults and they all do the same thing. 

### Reproducibility

Always

### Relevant Log Output

```shell
2022/01/12 15:43:18:119  domain changed from: Optional(nil) to: Optional(Optional(<NSFileProviderDomain: 0x105d19370, ScannedDocuments id=23B18009-8614-4576-8473-9E503C9BD8D4 (enabled)>))
2022/01/12 15:43:18:126  FPExt: itemChanged(at: file:///var/mobile/Containers/Shared/AppGroup/C7024043-D795-4FEC-B280-1B5E4949D399/File%20Provider%20Storage/23B18009-8614-4576-8473-9E503C9BD8D4/db.sqlite) called
2022/01/12 15:43:18:126  FPExt: persistentIdentifierForItem(at: file:///var/mobile/Containers/Shared/AppGroup/C7024043-D795-4FEC-B280-1B5E4949D399/File%20Provider%20Storage/23B18009-8614-4576-8473-9E503C9BD8D4/db.sqlite) called
2022/01/12 15:43:18:127  FPExt: item(for: NSFileProviderItemIdentifier(_rawValue: 23B18009-8614-4576-8473-9E503C9BD8D4)) called
```

**Comment by tobihagemann** [comment]
Shaking means "wrong password". Is it possible that you're using special characters that are somehow treated differently between Windows and iOS? This might be related: https://github.com/cryptomator/cryptomator/issues/1732
