### ISSUE TITLE
Disallow certain special characters in filenames

### ISSUE THREAD

**Issue by aryus96** [cryptomator/ios#152]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Renaming folder on IOS with character "/" broke the vault on Windows

### System Setup

- iOS: 2.0.0 (722)
- Cryptomator: 1.6.3 (Then updated to 1.6.5, problem persist)
- …

### Cloud Type

WebDAV

### Steps to Reproduce

1. Authenticate and unlock the vault of Cryptomator on IOS File App
2. Rename a folder by adding the character "/" in the name
3. Unlock the vault on Windows with Cryptomator 
4. The folder appear on Windows with the character ":" instead of "/"
5. Windows cannot create any folder inside this renamed folder. the following error comes up  "new folder error 0x8000ffff catastrophic failure"
6. I can list the files but I cannot access any file within that renamed folder on Windows but on IOS everything works fine.
7. I tried to duplicate the folder on IOS File App
8. The folder appears again with ":" character instead of "/" on his name on Windows, on IOS it's working fine. I have the same problem on Windows, cannot edit anything within the folder.
9. I created an other folder with a different name (without "/" character) on IOS Files within the Cryptomator Vault
10. Tried to copy the broken folder content to the new created one (Failed because of pCloud WEBDAV performances)
11. Now the root folder of the renamed folders appears to be **empty** on Windows. (Tried locking the vault, closing Cryptomator, reboot, ...)
12. The root folder is still accessible and all his files only on IOS File Apps

### Expected Behavior

- The renamed folder should include the character "/" and not ":"
- The folder on Windows should be accessible in read/write

### Actual Behavior

- First blocking Read and Write on Windows
- Then showing the root folder of the main one as empty 

### Reproducibility

Only once

**Comment by tobihagemann** [comment]
You're right, we should disallow certain special characters for filenames, which we're [already doing for the vault name](https://github.com/cryptomator/ios/blob/404dabbe5db5f12e945f5b6ba40cfdfc2677f288/Cryptomator/AddVault/CreateNewVault/SetVaultNameViewModel.swift#L36-L39).

Workaround: Rename the affected files on iOS to something else without the special characters.

**Comment by aryus96** [comment]
Yes I mean naming a folder with "/" knowing that it would work cross platform isn't the best idea I had but ...

Unfortunately now the workaround is too late as the problem evolved to show me an empty root folder. Do you have any leads to help me to solve that please ?
 
Because the only way to solve this now is to copy/paste each file in a new folder through IOS File App (not even whole folders cause Webdav pCloud works as a timeout request factory) and I have hundreds of files in this specific folder.

**Comment by tobihagemann** [comment]
I don't quite understand the situation. Can't you rename the folder with "/" on iOS to something different? What happens if you try that?

**Comment by aryus96** [comment]
Yes the root folder of the renamed folder still appears empty on Windows.

It's okay, I solved it by 

1. Downloading the vault on my linux
2. Unlocking the vault
3. Extracted the files from the corrupted root folder that appears empty on Windows 
4. Deleted the folder on Linux
5. Created the folder again with the good correct subfolder names (avoiding "/" character")

Thank you Tobias

**Comment by tobihagemann** [comment]
I must admit that I'm surprised that renaming the folder didn't work. 🤔 But glad you've found a different solution.

I'm reopening this issue because we'd still like to disallow these special characters. We'll close it after fixing it.
