### ISSUE TITLE
Cannot acces vaults on OneDrive any more: CryptomatorCloudAccessCore.OneDriveError-Fehler 0

### ISSUE THREAD

**Issue by speedmetalrolf** [cryptomator/ios#160]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Starting this morning I cannot unlock any of the vaults stored on my OneDrive. After unlocking, the Files app showed that the contents cannot be viewed because of an unknown error. When removing and trying to re-add the vaults in Cryptomator, trying to browse OneDrive results in an error: CryptomatorCloudAccessCore.OneDriveError-Fehler 0.

### System Setup

- iOS: 15.3
- Cryptomator: 2.1.0 (800)

### Cloud Type

OneDrive

### Steps to Reproduce

1. Add existing vault and choose OneDrive
2. Sign in with MS account
3. When browsing for the vault file, an error is shown:
![Uploading 30737809-2B97-484F-A261-BBCE60556064.png…]()

Can reproduce on iOS and iPadOS

### Expected Behavior

Vault file from OneDrive can be selected

### Actual Behavior

Error message

### Reproducibility

Always

**Comment by speedmetalrolf** [comment]
![BBC53873-7C15-4EF6-AFE8-9505C6A83E1F](https://user-images.githubusercontent.com/98789672/151916312-f6647914-80cd-4c93-8413-2ebc0c08ce86.png)

**Comment by speedmetalrolf** [comment]
I think this can be closed. After trying for several hours it seems to work again, so I assume this was a hicc-up in OneDrive.

**Comment by tobihagemann** [comment]
Thank you for reporting this issue. Unfortunately, the error code is ambiguous. There are a lot of instances in [OneDriveCloudProvider](https://github.com/cryptomator/cloud-access-swift/blob/2cb4002dab62082e7b6b548e5441a2014fa1cb90/Sources/CryptomatorCloudAccess/OneDrive/OneDriveCloudProvider.swift), which throws the `OneDriveError.invalidURL`. It may have been a server-side issue in OneDrive but that's hard to say. If that error comes up again and there is a way to reproduce the issue, please let us know!
