### ISSUE TITLE
Unable to open existing vault via WebDAV

### ISSUE THREAD

**Issue by christopherjones** [cryptomator/ios#164]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/cryptomator/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/cryptomator/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Unable to open existing vault via WebDAV

### What software is involved?

- Operating System: iOS 15.2.1
- Cryptomator: 2.1.0
- …

### Steps to Reproduce

1. Install Cryptomator 2.0+ on iOS
2. Add WebDAV connection
3. Navigate to vault location
4. Select vault?? You can’t. There’s no way to select the vault… app appears to be useless as there is no way to add a vault.

### Expected Behavior

I should be able to add an existing vault…

### Actual Behavior

I can’t open an existing vault via WebDAV connection.

### Reproducibility

Always

**Comment by tobihagemann** [comment]
Could you please let me know what _actually_ happens? What do you see instead? Cryptomator detects a vault if:

- either there is a folder `d` and a file `vault.cryptomator`
- or there is a folder `d` and a file `masterkey.cryptomator`.

Is that the case? What do you see if you navigate inside your vault?

**Comment by christopherjones** [comment]
Hi,

This is what I see:

**Comment by tobihagemann** [comment]
Interesting. I have a wild guess but that would mean that the WebDAV server doesn't respond accordingly. Do you have any more information on the WebDAV server?

**Comment by christopherjones** [comment]
I’m just using a standard install of FileRun, which has WebDAV built in.

**Comment by christopherjones** [comment]
> All right, I believe FileRun violates the [RFC 4918](https://datatracker.ietf.org/doc/html/rfc4918) standard but we'll fix it in the next update. I was able to reproduce the issue using FileRun's demo (thankfully, they had something like that).

Awesome, thank you for the quick response.
