### ISSUE TITLE
Add support for pCloud

### ISSUE THREAD

**Issue by peter25871** [cryptomator/ios#165]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

support pcloud on cyptomator 2

### Motivation

Hello,
Please support pcloud directly like  cryptomator of android. Ploud's webdav can't be connect, so I truly need directly support pcloud. Thanks for your help.

**Comment by tobihagemann** [comment]
Depends on https://github.com/cryptomator/cloud-access-swift/issues/3
