### ISSUE TITLE
Cannot save file until locking/unlocking (incl. document scanning)

### ISSUE THREAD

**Issue by sindastra** [cryptomator/ios#179]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Document scanning sometimes fails

### System Setup

- iOS: 15.3.1
- Cryptomator: 2.1.2 (838)

### Cloud Type

Dropbox

### Steps to Reproduce

1. Open Files app
2. Navigate to (unlocked) Cryptomator vault
3. Use the menu button (three dots in circle, top right)
4. Choose "Scan Documents"
5. Scan a document
6. Hit "Save"

### Expected Behavior

I expect to see a new PDF file named "Scanned Document" in my vault.

### Actual Behavior

Sometimes, instead, you'll briefly see a new file entry appear and disappear for a split second, i.e. it silently fails to save it seems. Once this occurs, it repeatedly occurs. What I figured works to fix it, is to lock and unlock the vault and try again. I believe this error might occur when one has set the "Unlock Duration" to "Indefinite", and it's been idling around for a while... That's just a guess, though.

### Reproducibility

Intermittent

### Anything else?

Being able to scan directly into Cryptomator is a nice side effect of integrating with the Files app, it gives you a Dropbox-like feature, but with privacy. ;D

**Comment by tobihagemann** [comment]
Thank you for reporting this issue! I'm unable to reproduce it though. In that case, maybe the log files contain something that we can work with. It might help if you can reproduce the issue with "Debug Mode" enabled.

https://docs.cryptomator.org/en/latest/ios/settings/#support

**Comment by sindastra** [comment]
Hi, I just tried it again, and it just so happened to happen again. :D 

So, I enabled the debug log, and this is what I got:

```
2022/02/23 15:50:01:071  itemChanged - failed to register file in upload queue with url: file:///var/mobile/Containers/Shared/AppGroup/***Redacted-UUID***/File%20Provider%20Storage/***Redacted-UUID***/db.sqlite and identifier: NSFileProviderItemIdentifier(_rawValue: ***Redacted-UUID***)
2022/02/23 15:50:06:689  FPExt: enumerator(for: NSFileProviderItemIdentifier(_rawValue: NSFileProviderRootContainerItemIdentifier)) called
2022/02/23 15:50:06:689  FPExt: item(for: NSFileProviderItemIdentifier(_rawValue: NSFileProviderRootContainerItemIdentifier)) called
2022/02/23 15:50:06:690  currentSyncAnchor for NSFileProviderRootContainerItemIdentifier called
2022/02/23 15:50:06:691  enumerateItems called for identifier: NSFileProviderItemIdentifier(_rawValue: NSFileProviderRootContainerItemIdentifier) - initialPage true
2022/02/23 15:50:06:695  readLock /(0x0000000104341320) called
2022/02/23 15:50:06:695  readLock /(0x0000000104341320) done
2022/02/23 15:50:06:695  readLock /(0x000000010402cae0) called
2022/02/23 15:50:06:695  readLock /(0x000000010402cae0) done
2022/02/23 15:50:07:097  enumerateItems returned 10 items for identifier: NSFileProviderItemIdentifier(_rawValue: NSFileProviderRootContainerItemIdentifier)
2022/02/23 15:50:07:116  Enumerate changes for: NSFileProviderRootContainerItemIdentifier anchor: Optional(2022-02-23 15:50:01 +0000)
2022/02/23 15:50:07:119  FPExt: urlForItem(withPersistentIdentifier: NSFileProviderItemIdentifier(_rawValue: 56)) called
2022/02/23 15:50:07:119  FPExt: item(for: NSFileProviderItemIdentifier(_rawValue: 56)) called
2022/02/23 15:50:26:399  FPExt: urlForItem(withPersistentIdentifier: NSFileProviderItemIdentifier(_rawValue: NSFileProviderRootContainerItemIdentifier)) called
2022/02/23 15:50:26:415  FPExt: importDocument(at: file:///var/tmp/com.apple.fileproviderd/***Redacted-UUID***/Scanned%20Document.pdf, toParentItemIdentifier: NSFileProviderRootContainerItemIdentifier) called
2022/02/23 15:50:30:077  FPExt: itemChanged(at: file:///var/mobile/Containers/Shared/AppGroup/***Redacted-UUID***/File%20Provider%20Storage/***Redacted-UUID***/db.sqlite) called
2022/02/23 15:50:30:077  FPExt: persistentIdentifierForItem(at: file:///var/mobile/Containers/Shared/AppGroup/***Redacted-UUID***/File%20Provider%20Storage/***Redacted-UUID***/db.sqlite) called
2022/02/23 15:50:30:078  FPExt: item(for: NSFileProviderItemIdentifier(_rawValue: ***Redacted-UUID***)) called
2022/02/23 15:50:30:081  itemChanged - failed to register file in upload queue with url: file:///var/mobile/Containers/Shared/AppGroup/***Redacted-UUID***/File%20Provider%20Storage/***Redacted-UUID***/db.sqlite and identifier: NSFileProviderItemIdentifier(_rawValue: ***Redacted-UUID***)
2022/02/23 15:50:30:778  FPExt: urlForItem(withPersistentIdentifier: NSFileProviderItemIdentifier(_rawValue: 56)) called
2022/02/23 15:50:30:778  FPExt: item(for: NSFileProviderItemIdentifier(_rawValue: 56)) called
2022/02/23 15:50:30:845  FPExt: urlForItem(withPersistentIdentifier: NSFileProviderItemIdentifier(_rawValue: 56)) called
2022/02/23 15:50:30:845  FPExt: item(for: NSFileProviderItemIdentifier(_rawValue: 56)) called
```

I hope this is of any use?

Note that, what solves this for me, is to manually lock and unlock the vault. Generally, when freshly unlocking the vault, this issue does not occur, but I set it to "Indefinite" unlock... And after some time idling around, issues start to arise with things not being able to be accessed in general. E.g. an app looking for a file in the vault might report it does not exist, even though I can see it in the Files app. Then locking and unlocking solves it.

Perhaps there's an issue with vaults that are unlocked indefinitely/idling around for long? Let me know if I should open an issue about that, or keep it to this particular issue here.

**Comment by tobihagemann** [comment]
Unfortunately, I can't see anything useful from this particular log. But since we're not really sure what the cause is, we can keep this issue. We'll keep investigating!

**Comment by tobihagemann** [comment]
I'm able to reproduce the bug but it's still quite tricky to debug since it's not easily reproducible. The only thing I noticed was "idling around" as well. However, in my case, it was slightly different. Only the "indefinite" vault didn't have this bug. All my other vaults (three of them) are affected by this that are set to "auto".

**Comment by sindastra** [comment]
For me, it happened with the "Indefinite" setting (that's the only one I used).
