### ISSUE TITLE
Fehlermeldung: Die Datei existiert nicht …

### ISSUE THREAD

**Issue by mahrens78** [cryptomator/ios#181]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/cryptomator/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/cryptomator/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Datei kann nicbt im Tresor gespeichert werden

### What software is involved?

- Operating System: iOS 15.3.1
- Cryptomator: 2.1.2 (838)

### Volume Type

WebDAV

### Steps to Reproduce

Datei über Dateien App in Tresor kopieren

### Expected Behavior

Anscheinend gibt es ein Problem mit der neuen Cryptomator App unter iOS.

Bei Versuch eine Datei über die Dateien App im Tresor zu speichern erscheint die Fehlermeldung

Die Datei existiert nicht: Die Datei test.pdf konnte nicht kopiert werden, da sie entwerder nicht existiert oder der Ordner, in den sie kopiert werden soll, nicht existiert.

Im Logfile erscheint folgende Fehlermeldung:
2022/02/24 21:34:11:880  itemChanged - failed to register file in upload queue with url: file:///var/mobile/Containers/Shared/AppGroup/

Über die alte Cryptomator App Version 1.6.2 (765)
konnte die Datei ohne Probleme gespeichert werden.

Erst nach einem Neustart des iPhones konnte die Datei mit der neuen Cryptomator App gespeichett werden.

### Actual Behavior

2022/02/24 21:34:11:880  itemChanged - failed to register file in upload queue with url: file:///var/mobile/Containers/Shared/AppGroup/

### Reproducibility

Intermittent

### Relevant Log Output

```shell
2022/02/24 21:34:11:880  itemChanged - failed to register file in upload queue with url: file:///var/mobile/Containers/Shared/AppGroup/
```

**Comment by tobihagemann** [comment]
Vielen Dank für den Fehlerbericht! Wir hatten jetzt einen ähnlichen Fall per E-Mail und der Nutzer hat eine interessante Beobachtung geschildert: Er hat die [Entsperr-Dauer](https://docs.cryptomator.org/en/1.6/ios/vault-management/) seines Tresors auf 5 Minuten eingestellt und konnte das Problem auf Anhieb nicht mehr reproduzieren.

Außerdem wären noch vollständigere Ausschnitte aus den Log-Dateien ggf. hilfreich, aber sicher sind wir uns da aktuell nicht. Wir konnten den Fall bisher noch nicht reproduzieren.

**Comment by mahrens78** [comment]
Bei mir steht die Entsperrdauer auf Auto. Ich werde die 5min Einstellung testen und ggf. weitere Logdateien zur Verfügung stellen.

**Comment by mahrens78** [comment]
- Debug Modus aktiviert
- Neuen Tresor TEST1 erstellt
	- Entsperrdauer: Auto
	- FaceID aktiv
- Tresor entsperrt
- 2 Dateien übertragen
- alle Apps geschlossen
- iPhone gesperrt
- gleiche Datei nochmal übertragen
- Fehler beim Speichern
	Die Anwendung hat noch erkannt das die Datei bereits exisitert.
	Also grundsätzlich scheint der Tresor noch geöffnet zu sein.
	Beim Versuch diese zu überschreiben kommt dann die Fehlermeldung
- Datei umbennant -trotzdem Fehler beim speichern
- Tresor gesperrt
- Tresor entsperrt
- Speichern von Dateien ist wieder möglich
- Debugmodus deaktivert

[logs_entsperrdauer_auto.zip](https://github.com/cryptomator/ios/files/8141184/logs_entsperrdauer_auto.zip)

**Comment by mahrens78** [comment]
Entsperrdauer auf 5 min umgestellt

Gleiches Problem, wenn man innerhalb der 5min bleibt.
Danach wird der Tresor automatisch gesperrt und nach einer erneuten Entsperrung
funktioniert das Speichern wieder.

Vielleicht noch wichtig:
Das Speichern der Dateien erfolgt über: Teilen / In Dateien speichern

Ein entsperren ist leider nur direkt über die Dateien App möglich.
Im Teilen Dialog bekommt man bei einem gesperrten Tresor nur die Meldung: 
Du musst dich authentifizieren, bevor du auf dieses Objekt zugreifen kannst.

**Comment by mludi** [comment]
Gleiches Problem. Einmal sperren/entsperren -> geht wieder.

**Comment by tobihagemann** [comment]
Ich markiere dieses Issue als Duplikat, weil ich mir inzwischen recht sicher bin, dass es sich um das gleiche Problem handelt wie bei #179, was schon vorher berichtet wurde. Ich lasse es aber erst mal offen bis wir die Ursache und eine Lösung gefunden haben.
