### ISSUE TITLE
Browsing directory in Google Drive fails with itemNotFound error

### ISSUE THREAD

**Issue by aseguramcgrew** [cryptomator/ios#194]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/cryptomator/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/cryptomator/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

When opening an existing vault in Google Drive, the app gives an error after most recent app update.

### What software is involved?

- Operating System: 15.4 (19E241) (iPhone 13 Pro Max]
- Cryptomator: 2.2.0
- Google Drive

### Steps to Reproduce

1. Click the plus sign to add a new vault.
2. Select Open Existing Vault
3. Select Google Drive
4. Select Account
5. Error Occurs

### Expected Behavior

Expected to show folders in my GDrive that will allow me to navigate to my vault. 

### Actual Behavior

I get this error each time.
![54658ABA-B89B-4C49-A099-C8800DB331D4](https://user-images.githubusercontent.com/102121019/159387217-0a7250a1-57f4-41ac-8861-053a8ffcec1c.png)

### Reproducibility

Always

### Relevant Log Output

```shell
2022/03/22 00:40:15:357  Error: itemNotFound(cloudPath: CryptomatorCloudAccessCore.CloudPath(path: "/"))
2022/03/22 00:41:11:729  Error: itemNotFound(cloudPath: CryptomatorCloudAccessCore.CloudPath(path: "/"))
2022/03/22 01:02:56:339  Error: itemNotFound(cloudPath: CryptomatorCloudAccessCore.CloudPath(path: "/"))
```

**Comment by tobihagemann** [comment]
Thank you for reporting this issue! My only theory right now is that you have a shortcut in your root directory that targets something, which doesn't exist anymore. If you can determine such a shortcut, you could try to remove it.

We'll fix this in the next update by skipping such shortcuts.
