### ISSUE TITLE
Add dir id file on directory creation

### ISSUE THREAD

**Issue by infeo** [cryptomator/ios#198]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Create on every directory creation a `dirid.c9r` file in case for recovery

### Motivation

See https://github.com/cryptomator/cryptofs/issues/113

**Comment by tobihagemann** [comment]
Depends on https://github.com/cryptomator/cloud-access-swift/issues/10

**Comment by tobihagemann** [comment]
Fixed in af2576384ea5a961ae2a228276e293967deee7c2
