### ISSUE TITLE
Protect main app itself via Password or Face ID / Touch ID

### ISSUE THREAD

**Issue by tobihagemann** [cryptomator/ios#207]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Add an optional feature to protect the main app itself via a password or Face ID / Touch ID.

### Motivation

Even though the contents of the vaults are protected, some users would also like to protect the main app itself. Sensitive information might include vault names/locations and also used cloud storage connections.

### Anything else?

Something to think about: If a user forgets their password, they should be able to "reset" the application. Or maybe it's not needed since they can always re-install the app.

**Comment by W3LLD0NE** [comment]
Any progress on this?

Also please note that until protected, everyone can access the app and not only read, but also remove vaults and other data.
This can be critical for example when user forgot the password and couldn't get into vault in other ways except using pre-configured FaceID auth on iPhone (to copy data and re-create the vault). This can be a problem in other scenarious as well.

**Comment by tobihagemann** [comment]
There is no progress since this is a feature request that hasn't been scheduled yet. We're currently working on other features that have a higher priority. If there is any progress, we'll keep this issue updated.

**Comment by tobihagemann** [comment]
This feature request is now obsolete with iOS 18. Here is how to lock your app with Face ID:

Long press Cryptomator app icon > Require Face ID
