### ISSUE TITLE
Remove "ghost" vaults in Files

### ISSUE THREAD

**Issue by badogski29** [cryptomator/ios#209]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Old vaults shows up in the Files after improper removal in the main app.

### System Setup

- iOS: 15.4.1
- Cryptomator: 2.2.3
- …

### Cloud Type

Google Drive

### Steps to Reproduce

1. Login to the main app
2. Open the Files app
3. Remove the main app without logging out/removing vault
4. Re-download the main app and login again
5. Previous vaults shows up, but can't be accessed. (error cryptomatorcommoncore.cloud-providerAcountError)
![IMG_33F6C813B270-1](https://user-images.githubusercontent.com/25316296/163743773-5ae63bb3-b32a-4e3a-b0f5-b1191a8ea6c9.jpeg)

### Expected Behavior

Previous vaults gets removed from the Files app

### Actual Behavior

Previous vaults shows up in the Files app

### Reproducibility

Always

**Comment by tobihagemann** [comment]
Thank you for your bug report! I guess we have to revert parts of d5fff9e0a0fb23492e097c71a44ce93c006af79f and d0a2f36f08f22fe36c3628ea3620009f2d339d8e then. Will be fixed with the next update!
