### ISSUE TITLE
iOS Live Photos

### ISSUE THREAD

**Issue by davyd15** [cryptomator/ios#210]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/cryptomator/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/cryptomator/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

The ability to add live photos to my vault

### Motivation

when i add photos in my iPhone to the Cryptomator vault via the files app, i get only the photo without the live photo, so the .mov file is missing. I would love to have my live photos backup up with cryptomator.

**Comment by tobihagemann** [comment]
Thank you for your feature request! But there's nothing that we can do here. In that case, you actually have to send a feature request to Apple. If you save a live photo to a different location in the Files app, you get the same behavior.

Workaround: Don't save the live photo directly but use "Save as Video" first. Then save the newly created video to the Files app.
