### ISSUE TITLE
Cannot restore purchase from previous iOS version of cryptomator

### ISSUE THREAD

**Issue by Mike-Sundays** [cryptomator/ios#214]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Cannot restore purchase from previous iOS version of cryptomator

### System Setup

- iOS: 15.1
- Cryptomator: 2.2.4

### Cloud Type

WebDAV

### Steps to Reproduce

1. Previous iOS version, Cryptomator Classic 1.6.3, is unlocked as full version.
2. Open Cryptomator 2.2.4, click on settings, and click on "Unlock full version" and on "Restore purchase"
3. Error message saying that no previous full version was found, even though there is an unlocked Cryptomator Classic version running on the same phone. 

### Expected Behavior

Unlocking the full version of the new Cryptomator app.

### Actual Behavior

"No previous full version was found" error, even though I have a previously unlocked version on the same phone.

### Reproducibility

Always

---

Can you help me? Thanks in advance :)

**Comment by tobihagemann** [comment]
Please select "Upgrade Offer" in your case.

**Comment by Mike-Sundays** [comment]
Yes, that was it. I was choosing the wrong option. Thanks again!
