### ISSUE TITLE
iOS Content Unavailable

### ISSUE THREAD

**Issue by Quorum75** [cryptomator/ios#215]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Content Folder Unavailable in iOS

### System Setup

- iOS: 15.4.1
- Cryptomato iOSr: 2.2.1 (892)

- macOS: 12.3.1
- Fuse: 4.2.5
- Cryptomator macOS: 1.6.8

### Cloud Type

OneDrive

### Steps to Reproduce

1. Add files in macOS Cryptomator folder
2. Check iOS Apple Files/OneDrive Cryptomator
3. macOS folder is present but the content is unavailable 

### Expected Behavior

Mirror between macOS and iOS folders and files.

macOS folder with content.
<img width="490" alt="Screenshot 2022-04-27 at 18 05 04" src="https://user-images.githubusercontent.com/49731083/165564615-e8cf2e4e-1d64-45ed-8cc3-b709b5eae596.png">

 iOS folder with unavailable content.
![IMG_1660](https://user-images.githubusercontent.com/49731083/165564887-a5ffe375-02c4-4109-88df-09e63a39b77f.PNG)

### Actual Behavior

iOS content does not show up on iOS.

### Reproducibility

Always

### Anything else?

This issue appears on other folders but not all of them. It is random and I can't find the pattern of the problem.

**Comment by SailReal** [comment]
Have you made sure that the iCloud sync client is running on your device and that the synchronization is completed?
