### ISSUE TITLE
3rd party apps do not have read/write access to Cryptomator vaults

### ISSUE THREAD

**Issue by MatejBz** [cryptomator/ios#216]
### Please agree to the following

- [x] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

When giving a 3rd party app (e.g. 1Writer) access to a folder to read from and write to, Cryptomator is grayed out. Apps can access only specific files inside the vault.

### System Setup

- iOS: 15.4.1
- Cryptomator: 2.2.4 (927)

### Cloud Type

OneDrive

### Steps to Reproduce

1. Open 1Writer (or Craft, Logseq or any other app that needs to be able to read data from and write data to a specific folder). 
2. Select "Add Folder". 
![F7D0E3BF-7996-46F4-A440-7F578FA39FC2](https://user-images.githubusercontent.com/9052087/165740227-45d2ec84-b26d-4ca8-a341-cd074221c90e.jpeg)

3. Select "Other..." 
![0904B87B-C8CE-4A6D-8C2E-F52AB10CA2F2](https://user-images.githubusercontent.com/9052087/165740364-e2b13a54-41f6-4fde-956e-f1a45ee18262.jpeg)

5. Cryptomator is grayed out in the Files app picker. 
![DE6F21DE-4036-4E05-9BAE-8DB85B9BCD9E](https://user-images.githubusercontent.com/9052087/165740395-462f3089-eb21-4f12-8505-c2e7519bedcc.png)

### Expected Behavior

Cryptomator **is not** grayed out and you can select it. 

### Actual Behavior

Cryptomator **is** grayed out and you cannot select it. 

### Reproducibility

Always

**Comment by overheadhunter** [comment]
@cryptomator/ios Same cause as in #48?

**Comment by MatejBz** [comment]
> @cryptomator/ios Same cause as in #48?

After reading that issue, I'd say the cause is the same. However, I'd change the title of either that issue or this one to make it more obvious that the issue is not isolated to just one app. 

Anyway, does that mean that we will never be able to use Cryptomator on iOS with apps that require folder access? Or is there perhaps a way to achieve it?

**Comment by phil1995** [comment]
> After reading that issue, I'd say the cause is the same. However, I'd change the title of either that issue or this one to make it more obvious that the issue is not isolated to just one app.

Exactly it is the same cause.
> Anyway, does that mean that we will never be able to use Cryptomator on iOS with apps that require folder access? Or is there perhaps a way to achieve it?

I wouldn't rule it out forever - however, as explained in #48, it is not feasible with the current FileProvider API. As soon as Apple updates the FileProvider API so that this feature can be implemented for a FileProvider with a cloud connection (which is what the FileProvider API was actually designed for), we will of course implement it.

**Comment by greedystack** [comment]
Hey! Any news about this? I saw that other apps with a cloud-/remote-connection can offer 3rd-party-access via file provider api
![image](https://user-images.githubusercontent.com/25386620/223000134-8cbfa0db-34ac-414e-a710-bb43414eee4e.jpeg)

**Comment by tobihagemann** [comment]
We've also discussed this in #51, maybe this will explain more. It's interesting to see that iSH also didn't implement this despite having asked this on Twitter (as linked in #51). We'll wait for official support from Apple.

**Comment by greedystack** [comment]
Thanks for your fast reply, @tobihagemann! Wouldn't it be a good compromise to implement this feature (when it's so easy to just add the `NSExtensionFileProviderSupportsPickingFolders` to `Info.plist`) and let the user decide in vault options wether he/she wants to enable it on her/his own risk?

**Comment by tobihagemann** [comment]
Because it isn't so easy. See: https://github.com/cryptomator/ios/issues/48#issuecomment-898377602
