### ISSUE TITLE
Wrong Date for uploaded Images with iOS Filesapp and Cryptomator

### ISSUE THREAD

**Issue by micha-09** [cryptomator/ios#231]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

An uploaded Image has no creation date and wrong change date

### System Setup

- iOS: 15.5
- Cryptomator: 2.3.0 (967)

### Cloud Type

WebDAV

### Steps to Reproduce

1. In iOS photos, select picture and save in files
2. Select folder in cryptomator vault and save file 

### Expected Behavior

The picture is encrypted and uploaded in the webdav target. The creation and changed date of picture is the same as in the original picture on the iPhone.

### Actual Behavior

The picture has no creation date and the changed date ist set to save time in vault.
For example the first picture shows the infos for the file on a local path in the files app on the iPhone, the second picture shows the infos for the same file in Cryptomator vault in the files app. On the first picture are correct dates set after save in files app.

First picture:
![IMG_0345](https://user-images.githubusercontent.com/803483/173238691-d1cbf419-abc5-4a94-8f45-e22d83d83f48.PNG)

Second picture:
![IMG_0344](https://user-images.githubusercontent.com/803483/173238701-24850b60-0bf7-435d-a54f-41ddeb8e1b5c.PNG)

### Reproducibility

Always

**Comment by Derad6709** [comment]
I use workaround: add time stamp to the filename via my auto upload shortcut.

**Comment by micha-09** [comment]
@Derad6709  Can you please post your shortcut?

**Comment by Derad6709** [comment]
https://www.icloud.com/shortcuts/adda4abe730842aca9dc82841f19a6d0

**Comment by micha-09** [comment]
Thanks a lot :)

**Comment by micha-09** [comment]
The Problem is not solved yet

**Comment by tobihagemann** [comment]
Sorry that we didn't give any feedback here. Unfortunately, there is nothing that we can do here due to the File Provider integration. Apple doesn't provide an API for adjusting the creation and modification dates.
