### ISSUE TITLE
iOS file edits are lost (Apple Numbers, PDF markups)

### ISSUE THREAD

**Issue by USER19464727** [cryptomator/ios#240]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/cryptomator/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/cryptomator/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

iOS edits in Apple Numbers revert back and changes are lost

### What software is involved?

- Operating System: iOS 15.5 on iPad Air 4.0 or iPhone 12 Pro
- Cryptomator: 2.3.0
- …

### Steps to Reproduce

1. Have a vault on Apple iCloud that is unlocked indefinitely
2. Open up an Apple Numbers spreadsheet within this vault
3. Edit this spreadsheet with some changes, such as typing new information in a new cell
4. Click "spreadsheets" to exit this spreadsheet and go back to looking at a list of possible files to open with Numbers
5. Notice that the modification date/time has updated to the current date/time
6. Turn off screen and do something else in the real world for a bit
7. Get back on the same (or different) device, navigate to this file, and notice the modification date/time has reverted back, even after making sure the folder has updated, such as by swiping the screen down
8. The changes made are no longer present and the modification date/time no longer matches the recent edits.

### Expected Behavior

After editing an Apple Numbers spreadsheet and exiting, I expect the changes to be saved, especially when the modification date/time seems to indicate it has saved.

### Actual Behavior

After editing an Apple Numbers spreadsheet, exiting, and returning later, the changes made were not saved. Sometimes the change do seem to save, but probably 75% of the time they do not.

### Reproducibility

Intermittent

**Comment by tobihagemann** [comment]
Since you've mentioned iCloud Drive, could you please check the following setting on your iPhone:

- Open iOS Settings
- Select "Cellular"
- Scroll to the bottom
- Check if you have iCloud Drive enabled

Just want to make sure that this is not a sync issue with iCloud Drive.

**Comment by USER19464727** [comment]
Yes, iCloud Drive is enabled there.

**Comment by USER19464727** [comment]
I now remember that I was having issues with a PDF and Apple Markup. I was marking up a PDF, closed it. I later came back and the changes did not save. This is likely the same issue.

**Comment by phil1995** [comment]
Just to be sure, you have unlocked the full version of Cryptomator 2? Furthermore, it would be great if you could send us the log files. How to export the log files from the Cryptomator 2.0 iOS app is described in the [documentation](https://docs.cryptomator.org/en/latest/ios/settings/).

You can either post them here in the thread or email them to us at [support@cryptomator.org](mailto:support@cryptomator.org). Please note that the logs can contain sensitive information like plaintext paths or filenames, etc.
You can send it to .

**Comment by USER19464727** [comment]
Yes both my iPhone and iPad use v2.3.0 currently. It's also on a MacBook, but that device is not used much and the vault is usually locked. I will export the logs I have right now, but I will also see if I can recreate the issue in a new Vault with a few test files to see if it happens there in a simplified test scenario where I can also have a better time stamp for when the issue occurred.

**Comment by USER19464727** [comment]
![EC91752A-0560-4ABE-9DFB-240916ACB44A](https://user-images.githubusercontent.com/96584065/187495024-946121cb-6fe8-4665-9c56-4f626ba95621.jpeg)

**Comment by USER19464727** [comment]
The two things in this issue and Issue #252 might all be related. Basically I'm working on a file, such as a Numbers spreadsheet and when I finish or navigate away, it says "Content Unavailable". I can only see folder contents if going the the Vault and navigating back to it. At some point later there might be (but not always) duplicated files created (like above). The changes I made to the file might or might not be saved. This combination of issues is making CM basically unusable for me at the moment. I did not seem to have these issues upon first rollout of CM2, although I don't know how much editing I was doing with Apple files.
I am sending some more logs.

**Comment by USER19464727** [comment]
Are other iOS users not having all of these issues? My devices are pretty standard and on the latest version. I created another fresh vault and have a single Numbers file in it that I've been using. I opened it the other day and, again, all my edits were lost. CM is completely unusable for me at the moment. I'm curious why my situation is (apparently) unique?
