### ISSUE TITLE
Files missing / invisible

### ISSUE THREAD

**Issue by patrickap** [cryptomator/ios#247]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

If I open my vault using Cryptomator 2 on iOS some files are missing / invisible. If I do the same using Cryptomator 1 for iOS they are visible.

### System Setup

- iOS: 15.4.1
- Cryptomator: 2.4.1

### Cloud Type

iCloud Drive

### Steps to Reproduce

1. Open vault on Cryptomator 2 for iOS
2. View folder content -> some files missing
3. Open vault on Cryptomator 1 for iOS or Cryptomator for macOS -> missing files visible

### Expected Behavior

It should show all files.

### Actual Behavior

Some files are missing / hidden. It is always the same files.

### Reproducibility

Always

**Comment by nano9g** [comment]
I'm having this issue as well.

**Comment by patrickap** [comment]
I was able to identify and solve the problem. It seems to be an iCloud Drive sync issue. In the iOS Files app search for the appropriate vault folder and long tap it. There's an option "Load now" which should start a new sync.
