### ISSUE TITLE
Add ability to share files from other app

### ISSUE THREAD

**Issue by krisfield** [cryptomator/ios#250]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Allow for sending files from another app

### Motivation

I use a scanner app to digitize documents on ios. Using the ios share button pulls up options such as to share with another app or  “save to files”.

The “save to files” feature doesn’t work because I can only navigate to the locked vault in that file interface. 

### Considered Alternatives

Can Cryptomator be added to list of apps to be shared with from other apps so i can scan and transfer pdfs/images directly to my vault?

**Comment by tobihagemann** [comment]
You should be able to select a Cryptomator vault via "Save to Files".

Did you enable Cryptomator in the Files app? https://docs.cryptomator.org/en/1.6/ios/access-vault/#enable-cryptomator-in-files-app

**Comment by krisfield** [comment]
I do have it enabled but I figured out my issue. In “save to files” I had navigated to the Cryptomator folder under icloud. I had to go up a level to select “Cryptomator” at the Browse Location.

Not sure how I missed that. Thank you for following up, the app is great.
