### ISSUE TITLE
Syncing with iCloud not working properly

### ISSUE THREAD

**Issue by dasampson** [cryptomator/ios#251]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/cryptomator/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/cryptomator/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Not all files appear synced to iCloud though the app indicates that.

### What software is involved?

- Operating System: iOS 15.5
- Cryptomator: 2.4.1

I'm using the new integration with the files app to upload photos in batches (20 to 100 photos, usually around 60). In the UI there are 920 photos, but on my iPad I see 869 and on my mac 880 synced and then the count went down to 879 for some reason. Most of the photos have the option to download from iCloud in the files app despite the fact I can't see them on other devices. 

### Steps to Reproduce

1. Set iOS to export photos as JPEG.
2. Upload 20-100 photos (note: these are not live photos) using the files app integration. 
3. Wait for things to sync (have fun figuring out what the progress is on that because there's no indicator anywhere).
4. Try to find these photos on another device (iPadOS or macOS) and be disappointed and confused that they aren't all there. 

### Expected Behavior

All photos should sync to iCloud and be available on other devices. 

### Actual Behavior

Photos randomly don't sync. There does not appear to be a pattern. I had 1-2 HEIC photos and one video, but these did not appear to cause any issues since they were available on other devices. The issue appears to be that when you're uploading a number of files some just never make it to iCloud even though the UI implies that they're uploaded.

### Reproducibility

Intermittent

**Comment by tobihagemann** [comment]
Cryptomator for iOS actually doesn't "sync" with iCloud Drive. And it sounds like a sync issue, where we don't have much control over. There is one setting though that may improve iCloud Drive sync: Go to iOS Settings > Cellular > scroll to the bottom > Enable iCloud Drive (if it isn't already).

**Comment by dasampson** [comment]
I put on my QA hat and I tried something else. I used my mac mini to upload jpeg images 100 at a time. Each time I waited for iCloud to indicate that the upload had finished before starting the next batch. After I uploaded 895 photos I waited a couple hours and then attempted to view the photos in the file app. I was surprised to see that on both my iPhone and iPad it showed a total count of 879 photos in the folder. I scrolled until I found one missing and then opened up the V1 Cryptomator app to check the same folder from the same iPad. The missing file was visible there. I noticed the same file was also missing in the files app on my iPhone. There seems to be some bug in the files app integration that produces the exact same result on both devices.

It gets more interesting. After opening the "missing" file in Cryptomator V1 it was visible in the files app and the total file count increased by one to 880. I found another "missing" file and viewed it in V1 before going back to the files app. When I tried scrolling I got an error saying that the content wasn't available. I had to re-enter the vault and when I went back to the folder the "missing" file was present. 

I can't discern any pattern for why these photos look like they're not there. They seem to be scattered randomly i.e. files numbered 881 and 755 appeared "missing" on my iPad and iPhone in the files app. But these images were both taken with my iPhone and they are all the same format with similar, sequential filenames. One was 4MB and the other 6.8MB.

I opened another folder of pictures from when I studied in Germany in 2010 (files are smaller and have been in the vault for years). It contains 803 files (all my photos are sequentially numbered), but the count in the files app is 791. 

If a folder contains a couple hundred files some will appear missing in the files app. If you upload large numbers of files using the files app they don't all get enumerated on other devices. There does not appear to be a sync issue with the files themselves, only with the files app integration. It seems like some index isn't getting updated or read properly, depending. 

All devices (2018 mac mini, iPhone 13 Pro, and 2018 iPad Pro 11-inch) were running latest version of their respective operating systems and the latest app versions.

**Comment by dasampson** [comment]
Hit comment instead of reopen.

**Comment by clemensbartz** [comment]
I do share the same symptoms when uploading a large number of files (for me it was all of the files from a different vault to the new one in iCloud Drive).

Another observation: In addition to the original report, I am missing whole folders. Interestingly enough, when I deleted some of the directories on the Mac app (WebDAV), the delete went through more quickly than for the synced folders although the size of the non-visible folders is many times larger than the synced one. One a second try, I could not replicate the same behavior.

**Comment by USER19464727** [comment]
On my iPad and iPhone I can see files as expected (aside from issues I have posted about). On my macbook, though, various files just don't show up. If I force sync my entire vault folder on iCloud it looks like they start showing up. However, I will not always have HD space on my macbook to download the entire vault. I could create several vaults. Anyways, I would expect all files to show up even if they are not downloaded from iCloud. It makes it look as if I'm missing files, but then I go to my iPad and I see them. I feel like this is related to sync issues (hence posting here), but possibly not.

**Comment by krl91** [comment]
Same kind of problem between macos 12.6.5 with crytptomator 1.8.0 macintel and ios  16.4.1:
some files exist on ios (paed version), but had been deleted on MacOS ... that sound to be critical....
