### ISSUE TITLE
Vault on iOS shows every file and folder twice, temporarily

### ISSUE THREAD

**Issue by USER19464727** [cryptomator/ios#255]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

After various actions, such as leaving the Files app and returning, my Vault shows all files and folders listed twice. Navigating away and returning returns it to a normal view.

### System Setup

- iOS: 15.6.1
- Cryptomator: 2.4.1

### Cloud Type

iCloud Drive

### Steps to Reproduce

1. Do things with files in the vault
2. Leave the Files app
3. Return to the Files app to the last view and all files and folders show a second copy of each
4. Change to another app
5. Return to the Files app and the proper list of files and folders is shown

### Expected Behavior

I do not expect to see "apparently" duplicated files when returning to the Files app.

### Actual Behavior

Files look as though they were duplicated, although all with the same name.

### Reproducibility

Intermittent

**Comment by USER19464727** [comment]
Rebooting my iPad seems to have fixed this for now. Not sure why it started happening in the first place...

**Comment by USER19464727** [comment]
Still occurring. Also on my iPhone. See photo.
![7335A3F9-D82C-44B5-ABB2-1CB33FACABD1](https://user-images.githubusercontent.com/96584065/187494642-7259e52c-cd4f-48ee-ada7-f2a0626a7287.jpeg)

**Comment by phil1995** [comment]
Could you provide some logs? Either by posting them here (but be aware that they contain the plaintext paths and the name of your vault) or sending them to info@cryptomator.org

Otherwise it's hard to find the root cause as I could not reproduce it.

**Comment by USER19464727** [comment]
I'll send some logs next time it happens--it's not occurring today.
