### ISSUE TITLE
Cryptomator 2 app not working on new iOS

### ISSUE THREAD

**Issue by ganjim** [cryptomator/ios#260]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/cryptomator/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/cryptomator/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Cryptomator 2 app not working on new iOS

### What software is involved?

- Operating System: iOS 16
- Cryptomator: 2.4.0
- …

### Steps to Reproduce

1. Upgrade iPhone to iOS 16
2. try copying something into a Cryptomator vault
3. …

### Expected Behavior

I expected vaults to be accessible as always

### Actual Behavior

The vault doesn’t open. It doesn’t even ask me for the faceid. I had to install the original Cryptomator app to be able to work with my vault

### Reproducibility

Always

**Comment by tobihagemann** [comment]
I'm unable to reproduce the issue. Have you tried to update Cryptomator to 2.4.1?

**Comment by USER19464727** [comment]
FWIW, Cryptomator 2 is working for me on iOS 16 on iPad and iPhone, but my open issues persist.

**Comment by ganjim** [comment]
I am actually on 2.4.1 sorry. Still having those issues
