### ISSUE TITLE
Couldn't communicate with a helper application

### ISSUE THREAD

**Issue by serranomorante** [cryptomator/ios#261]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Couldn't communicate with a helper application.

### System Setup

- iOS: 16.0
- Cryptomator: 2.4.1 (997)
- iPhone Files App

### Steps to Reproduce

1. Go to your folder. Doesn't matter if you go directly from the iPhone files app, or the cryptomator 2 app.
2. Press and hold any of your files.
3. Click on any cryptomator action like "Clear from Cache"

The result: Couldn't communicate with a helper application.

### Expected Behavior

It worked before the IOS update.

### Actual Behavior

Couldn't communicate with a helper application.

### Reproducibility

Always

**Comment by serranomorante** [comment]
Hi. I uninstalled cryptomator from my iPhone then install it again. Signed in to my webdav again, open my existing vault and now is working fine.

**Comment by joshirio** [comment]
I have the same problem. The following happened: after the iOS update to version 16, Cryptomator lost somehow the license key activation, saying my trial period ended. No big deal, just tapped the "restore activation" button inside the Cryptomator app.

The Issues is, that while Cryptomator was not activated (key lost), I uploaded 2 files via the standard iOS files app, but the upload was never completed and the files are greyed out (with an error icon). I can't get rid of those files now from within the files app, because every action files.

**Comment by Torch0000** [comment]
Is uninstalling and reinstalling the app the only fix for this?

**Comment by phil1995** [comment]
> I have the same problem. The following happened: after the iOS update to version 16, Cryptomator lost somehow the license key activation, saying my trial period ended. No big deal, just tapped the "restore activation" button inside the Cryptomator app.
> 
> The Issues is, that while Cryptomator was not activated (key lost), I uploaded 2 files via the standard iOS files app, but the upload was never completed and the files are greyed out (with an error icon). I can't get rid of those files now from within the files app, because every action fails.
> 
> ![screen](https://user-images.githubusercontent.com/12795018/192740940-61610c98-f2cb-47f4-ac27-89d116957050.png)

Did you try to restart the upload via the action menu (tap and hold onto the item)?
If this also fails could you please provide us the log files?

**Comment by phil1995** [comment]
> Is uninstalling and reinstalling the app the only fix for this? I get this error frequently

If you get this error frequently, please provide us some more details (like cloud provider, os version and especially enabling the debug mode and send us the logs - see https://docs.cryptomator.org/en/latest/ios/settings/#support for more details).

**Comment by Torch0000** [comment]
Hi,

I am using pCloud as my provider. I am using iOS version 14.8.1 on my IPhone 12 Pro Max. I am using Windows 11 on my HP Envy laptop. I just enabled the debug mode. Included are the logs. The files are all working on my desktop app. This is where I normally go to replace files that did not save properly when I tried to add them to the phone app. Here also is a screenshot of the type of messages I get when it doesn’t save properly. After I have replaced the error files from the iPhone app with working copies on my PC, the iphone app still shows this error for them.

**Comment by tobihagemann** [comment]
@Torch0000 Your attachments (logs and screenshot) didn't arrive at GitHub. It would be great if you could add them via GitHub (not email). Thank you!

**Comment by joshirio** [comment]
> Did you try to restart the upload via the action menu (tap and hold onto the item)?
> If this also fails could you please provide us the log files?

OK, I remember the first time I tried, it failed to re-upload. Now it did work, without issues and the files have been correctly uploaded to the cloud. All good, thanks.

**Comment by tobihagemann** [comment]
I'm under the impression that this issue contains several non-related issues that have been resolved (somehow). Closing this for now. If this happens again, please create a new issue and make sure to attach a debug log.

**Comment by tomazmarkelj** [comment]
Have same error on iPad 6th gen, iOS 16.3, cryptomator ios 2.4.5. It was working fine one previos IOS version.

I tried: deleted the app, re-installed, re-created webdav and re-added the vault, the helper error was displayed again

Additionaly I am missing the cryptomator icon on the Files sidebar, it shows the default one (white background with some circles).
![2023-01-27_19-13-08](https://user-images.githubusercontent.com/114357562/215163287-23d538bd-29fb-43cd-8ca0-e1bf3aeb50e8.jpg)
![2023-01-27_19-14-00](https://user-images.githubusercontent.com/114357562/215163290-5668fb05-4835-4df9-a7f1-68ea22cb0143.jpg)
