### ISSUE TITLE
Unable to open vault

### ISSUE THREAD

**Issue by Klkcl** [cryptomator/ios#268]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/cryptomator/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/cryptomator/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Vault opening cancelled / unable to open vault via Files app with password or FaceID

### What software is involved?

- Operating System: iOS 16.0.3
- Cryptomator: 2.4.1 (997)
- …

### Volume Type

WebDAV

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. …

### Expected Behavior

Vault opens after password 

### Actual Behavior

Vault opening cancelled / unable to open vault via Files app with password or FaceID

### Reproducibility

Always

### Relevant Log Output

```shell
NA
```

### Anything else?

NA

**Comment by tobihagemann** [comment]
Can you please check out the log file for more information? https://docs.cryptomator.org/en/latest/ios/settings/#support
