### ISSUE TITLE
Data Connection required

### ISSUE THREAD

**Issue by RainrZufall** [cryptomator/ios#269]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/cryptomator/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/cryptomator/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

A data/internet connection is required to access locally stored data

### What software is involved?

- Operating System: iOS 16.x
- Cryptomator: Cryptomator 2 2.4.1

### Steps to Reproduce

1. save a vault locally
2. open the vault
3. enable AirPlane Mode / disable data connections
4. try to access/decrypt a file thats not already cached

### Expected Behavior

Locally stored files can also be decrypted without a data/internet connection.

### Actual Behavior

Decryption is not possible without a data/internet connection.

### Reproducibility

Always

### Anything else?

![IMG_2715 (Klein)](https://user-images.githubusercontent.com/116357136/197711366-bf5adba4-48f8-438f-a7b5-a2dcff425b46.PNG)

**Comment by tobihagemann** [comment]
Unfortunately, we can't change this behavior because the Files app seems to require an internet connection when tapping on a document that has the cloud icon. But I've found a workaround.

## Workaround

Long press on the document and select "Download Now".

**Comment by RainrZufall** [comment]
> ... the Files app seems to require an internet connection when tapping on a document that has the cloud icon. ...
Makes sense 😅

Thanks for the tip with the "long press" Works great
