### ISSUE TITLE
iOS automatic photo upload

### ISSUE THREAD

**Issue by ueismann** [cryptomator/ios#271]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

I used shortcut and automation as suggested on the Cryptomator website, and have the shortcut executed every night. However most of my photos do not get uploaded, although I limited the number of pics to significantly less than 100 (default was 120 from the shortcut). Actual daily number of pics is on the order of 10, and only a fraction gets uploaded. Of course, manual uploading of the pics with the one-way-street-sign is possible, but quite tedious and not in the true sense of cloud integration of photos or automation in general.

### System Setup

 iphone 12 iOS 15.6.1 
 cryptomator 2.4.1(997) 
 nextcloud via WebDAV from hosting.de

### Steps to Reproduce

Set up as described and have the automation running.

### Expected Behavior

Photos get uploaded.

### Actual Behavior

They don't get, actually.

### Reproducibility

Intermittent

**Comment by phil1995** [comment]
I agree that the current workaround by triggering a re-upload for each item manually is quite tedious. As #272 is a bit more broad and fully includes your described issue I'll close this one in favor of #272.
