### ISSUE TITLE
iCloud Drive extremely slow because of Cryptomator 2 on iOS 16 

### ISSUE THREAD

**Issue by ur2390** [cryptomator/ios#273]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/cryptomator/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/cryptomator/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

iCloud Drive is extremely slow because of Cryptomator 2 on iOS 16

### What software is involved?

- Operating System: iOS 16.1 (iPhone and iPad)
- Cryptomator: 2.0
- Vault in iCloud Drive
- encrypted cryptomator vault inside iCloud Drive, with many folders and files, ranging from millions of files of less than 1KB, to some individual media files about 7.5-8GB large, total encrypted storage in the range of 600-700GB

### Steps to Reproduce

1. Install iOS 16.1
2. Link an iCloud (Drive) account that has a Cryptomator Vault (mine is 500GB large)
3. Link Cryptomator 2 to this drive
4. Since the .dir files are not yet downloaded from the cloud to be able to point Cryptomator 2 to the right file tree head, and we can't know which .dir file from the cryptomator folder is the root one, either wait until they are downloaded, or force the appropriate files to download by using Cryptomator 1 which seems to be able to trigger the iCloud Drive download of the .dir file when entering the root folder (or any folder for its subfolders)
5. Try to move any file in iCloud Drive between two random folders (outside of Cryptomator), this should be extremely slow (instead of a second, it would take 2-3 minutes)
6. Same as 5, try to save an attachment from the email to a folder in iCloud Drive, same problem
7. The bad behavior seems to be avoided when downloading files from Safari, or when using 3rd party file managers like FileBrowser
8. The biggest problem remains 6, but also 5, and effectively this renders iCloud Drive unusable.
9. Delete cryptomator 2 completely and the behavior will revert to the correct one. If it doesn't, unlink icloud drive and re-link-it, and it will work fine.

### Expected Behavior

Cryptomator 2 on iOS 16 should not clog the system, and should work well just as it did on iOS 15.
Side Note: even on iOS 15, there were sometimes issues when Cryptomator would disconnect, or show duplicate folders (even if on the drive there were a single copy), but generally the behavior was ok.

### Actual Behavior

On iOS 16, using iCloud Drive is severely impacted.

### Reproducibility

Always

### Anything else?

I have no idea how to interpret this, albeit I am a computer scientist. My best guess is that somehow Cryptomator's cache processing may be affected by certain changes in the handling of the cloud operations in ios16 vs ios15, and the cache engine somehow keeps syncing and using iCloud Drive "energy" which impacts general iCloud Drive performance. 

Apple is known to change dramatically engines and syncs from one iOS to another, sometimes so dramatically that backward compatibility with older versions is often lost.

Also please note that as opposed to iOS 15, on iOS 16 it happens way more often that cryptomator lists a folder with a message that the content is unavailable, as well as showing folder contents 2-3-4 times (especially after a large local download / sync of cloud-only data)

**Comment by phil1995** [comment]
Thanks for reporting this issue @ur2390!
May I ask what you exactly mean by:
> 3. Link Cryptomator 2 to this drive

Do you mean that you only added the vault in the main app or did you actually try to unlock the vault the first time in the Files app?
Could you also give us the amount of folders in your vault root directory? Because I currently suspect that this has to do with the "fake" pagination we introduced to fix the memory problem in the FileProvider in connection with vaults with many items (#244). However, as we only acquire a read lock for the root of the vault when unlocking the vault the iOS filesystem _should_ be smart enough to not clog the rest of the filesystem.

**Comment by ur2390** [comment]
vault folder structure:
1 single folder (root level) and then inside it 
6 folders
and these start having more subfolders etc.

I am not sure what you mean with your first question. What I wanted to say with "link" was opening cryptomator 2, selecting to open an existing vault, then choosing iCloud, then choosing the folder that contains the vault metadata

I don't think I ever unlocked the vault first from the files app. I usually do the steps detailed above and cryptomator 2 asks for the vaults password. then I go into the vault settings to check the use touch/face ID which requires the password again, and then start files for the first time.

further along using the vault, I sometimes go back to choose Indefinite duration for vault staying open, and sometimes I choose Auto / let iOS decide.

rarely I also clear the cache in Cryptomator 2

other than those, it's all work from the files app (except using cryptomator 1 for the reasons explained in the main post)

reminder that my vault is huge, 700GB and is mixed from millions of small files (e.g. programmint language code) to large size unique media files such as 8GB 4K recorded videos.
