### ISSUE TITLE
No confirm button for webdav (iPad Pro)

### ISSUE THREAD

**Issue by mikeandreiabano** [cryptomator/ios#280]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/cryptomator/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/cryptomator/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

When adding a webdav source on iPad pro, confirm button is missing.

### What software is involved?

- Operating System: iPad Pro iOS 14
- Cryptomator: 2.4.2
- …

### Volume Type

WebDAV

### Steps to Reproduce

1. Add a vault
2. Open existing vault
3. Click webdav
4. Insert credentials
5. No confirm button

### Expected Behavior

Confirm credentials and create vault.

### Actual Behavior

Confirm button missing.

### Reproducibility

Always

### Anything else?

![IMG_1588](https://user-images.githubusercontent.com/107393574/205459921-580841f2-505a-4fe2-93b5-111eafd4ddd3.png)

**Comment by phil1995** [comment]
Can be reproduced very easily with an iOS 14 device.

**Comment by tobihagemann** [comment]
Out of curiosity, does it work if you press the return key on the keyboard (when the password field is selected) to confirm the credentials?

**Comment by mikeandreiabano** [comment]
> Out of curiosity, does it work if you press the return key on the keyboard (when the password field is selected) to confirm the credentials?

Hi. Tried and confirmed that pressing return key does not work when all credentials are filled out and password field is selected.
