### ISSUE TITLE
Camera uploads

### ISSUE THREAD

**Issue by fabriziobagala** [cryptomator/ios#286]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/cryptomator/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/cryptomator/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Camera uploads is a feature that automatically uploads photos from your mobile device to cloud storage provider (OneDrive, iCloud, etc.) in an encrypted way

### Motivation

This feature is useful for all users who take photos right from their own device (tablet or smartphone) and want to save their memories from prying eyes.

### Anything else?

https://support.boxcryptor.com/en/help/work-with-files/ios/#camera-upload

**Comment by tobihagemann** [comment]
This is already possible via Apple's own Shortcuts. Check out our guide! https://docs.cryptomator.org/en/latest/ios/shortcuts-guide/
