### ISSUE TITLE
Files app shows files after vault timed out and locked. 

### ISSUE THREAD

**Issue by gitbq** [cryptomator/ios#287]
When using cryptomator 2, even when the vault has auto locked, the most recent opened file is visible  files app when using the app switcher, and is also visible for a few seconds when switching back to the files app, even though the vault has timed out and locked.

Preferred behaviour:

(1) The files app, when using the app switcher,  blurs any content related to the cryptomator vault, including the currently opened file. 

(2) the files app does not show the currently opened, or last opened file for any time. After the vault has timed out and locked, there is no file displayed for any time when opening the files app. The files app should only show the "unlock required" screen.

V2.4.3
Ipad mini 6

**Comment by tobihagemann** [comment]
Unfortunately, that's not possible. We don't have _that much_ control over the Files app and its UI. If it is somehow technically possible, we'd be glad to implement it.
