### ISSUE TITLE
Add ability to stream video files

### ISSUE THREAD

**Issue by websnowtea** [cryptomator/ios#289]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Add ability to stream video files without downloading the entire file

### Motivation

It will be great if a large file can be played, streamed (buffered) without waiting for the entire file to get downloaded. 
Please check this project that has the ability to do that: https://github.com/lithium0003/ccViewer
Thank you!

### Considered Alternatives

wait for the entire file to get downloaded

**Comment by phil1995** [comment]
Unfortunately this is not possible  as the FileProviderExtension does not support any form of streaming (yet) and just waits until a file has been fully downloaded.

**Comment by starn** [comment]
Hi,

As mentioned by another comment the iOS file app integration does now allow streaming, that is why you need a third party app.

I built a iOS and appleTV for what you need: its name « cloud media streamer » on the App Store.
Support many clouds, Cryptomator vaults,  thumbnails and streaming videos

**Comment by rob151515** [comment]
Just wanted to add that this feature would be fantastic to have in the IOS app, if it’s now possible.

**Comment by starn** [comment]
> Just wanted to add that this feature would be fantastic to have in the IOS app, if it’s now possible.

The integration in “File” on ios does not allow streaming, that’s why the feature does not exist and I created a dedicated app to stream videos and music https://app.starn.fr

**Comment by rob151515** [comment]
> > Just wanted to add that this feature would be fantastic to have in the IOS app, if it’s now possible.
> 
> The integration in “File” on ios does not allow streaming, that’s why the feature does not exist and I created a dedicated app to stream videos and music https://app.starn.fr

Ah I see, thanks. was confused by the typo in your original comment ‘does now allow streaming’.
