### ISSUE TITLE
Adding WebDAV connection stuck at "Authenticating…"

### ISSUE THREAD

**Issue by tobihagemann** [cryptomator/ios#295]
Follow-up on: https://github.com/cryptomator/ios/issues/291#issuecomment-1398191465

Summary: While trying to add a WebDAV connection using a self-signed certificate (or maybe due to a different cause, I don't know), Cryptomator gets stuck at the "Authenticating…" progress.

I don't believe that it's a regression introduced in 2.4.4 but it's quite possible that it didn't work before either, see: https://www.reddit.com/r/synology/comments/108i5zm/cryptomator_2_accessing_from_ios_with_2fa_via/

I'm having a major déjà vu feeling but I was unable to find the issue/commit I was thinking of. Didn't we have this problem in the past and solved it somehow? Or maybe not, I'm confused.

Btw, I was unable to reproduce this issue with "regular" WebDAV connections. And I haven't reproduced this issue myself either, I'm just reporting the bug as experienced by others.

**Comment by tomazmarkelj** [comment]
i had a webdav connection setup prior to 2.4.4 and is working fine after upgrading to 2.4.4, re-editing the webdav source gives me a nice authenticating and then a checkmark.

tried with a fresh 2.4.4. on a new device, stuck on authenticating.

**Comment by tobihagemann** [comment]
We've already found the cause and will have a solution available soon! Unfortunately, this requires an update and there is no workaround.

(And yes, as suspected, it has something to do with self-signed certificates and I was able to confirm this issue.)

**Comment by ddulic** [comment]
Thank you very much @tobihagemann 

I can confirm this fixes the issue!
