### ISSUE TITLE
WebDAV vaults open very slowly under iOS

### ISSUE THREAD

**Issue by 25-Mars** [cryptomator/ios#303]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/cryptomator/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/cryptomator/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

WebDAV vaults open very slowly under iOS

### What software is involved?

- Operating System: iOS 16.3 
- Cryptomator: 2.4.6
- WebDAV IceDrive
- AdGuard

### Volume Type

FUSE

### Steps to Reproduce

1. Open Cryptomator app
2. Menu --> Open vault in Files app
3. Touch ID, password (doesn't matter)

### Expected Behavior

Vault opens immediately and shows contents

### Actual Behavior

Vault opens very slowly and displays content also very slowly.
Takes about 1-2min with an empty folder in the vault. The problem only occurs with WebDAV!
On the PC, everything opens quickly.

### Reproducibility

Always

**Comment by phil1995** [comment]
Could you please provide logs?

**Comment by 25-Mars** [comment]
[Logs.zip](https://github.com/cryptomator/ios/files/10705930/Logs.zip)

Im Augenblick ist Icedrive schwierig...
Nachdem durch meine Rumprobiererei alles immer schlimmer wurde (nix ging mehr), habe ich die Containerverknüpfung gelöscht, neu verknüpft und Telefon neu gestartet. Jetzt öffnet sich der Container wenigstens wieder, allerdings immer noch recht langsam (zähflüssig).
Am PC ist alles schnell und flüssig.

**Comment by 25-Mars** [comment]
Hello,
the problem has somehow resolved itself.
Just opened the container (vault) at Icedrive via WebDAV again and everything is now fast and smooth. I hope it stays like this ;-)... 
Thanks and greetings

**Comment by 25-Mars** [comment]
Hello,
of course it does not work today.
I went to the trouble of removing Cryptomator and reinstalling it later, setting up all the vaults again, etc.

With Icedrive with WebDAV again everything is extremely tough and then hangs in my opinion. You can then neither lock nor reopen in the files app. This is only with Icedrive (Cryptomator for iPhone) so and I do not know with whom it hakt. Whether it's on my end, their end, or in Cryptomator....

Logs von heute:
[Logs.zip](https://github.com/cryptomator/ios/files/10713495/Logs.zip)

**Comment by phil1995** [comment]
In order to do a folder listing we need to execute the following (serial requests):
1. PROPFIND 
2. GET 
3. PROPFIND
According to the logs from 11.02.2023 it took ~10s to even download the very small .dir9cr file and 14-24s for each propfind request. So I guess the cause of your issue is that Icedrive is rather slow and unfortunately there isn't much we can do to improve this.

**Comment by tobihagemann** [comment]
As @phil1995 has mentioned, Cryptomator performs the operations it has to do and it's up to the server to respond quickly. Unfortunately, nothing we can do here from our side.
