### ISSUE TITLE
Add MacOS Catalyst Support

### ISSUE THREAD

**Issue by davidashman** [cryptomator/ios#321]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Create Catalyst binary to leverage FileProvider on MacOS

### Motivation

The main Cryptomator application is built to be a cross-platform solution.  With that, it's not a truly native MacOS application.  MacOS users run into issues related to kext support (Ventura, M1) and FUSE-T instability because it's trying to be cross-compatible.  There is already an excellent FileProvider implementation in the iOS app.  Adding a MacOS-compatible interface would be incremental for this app.

**Comment by tobihagemann** [comment]
Cryptomator for iOS uses [NSFileProviderExtension](https://developer.apple.com/documentation/fileprovider/nsfileproviderextension), which is not compatible with macOS. This was the only choice when we started this project.

For macOS, we would have to use [NSFileProviderReplicatedExtension](https://developer.apple.com/documentation/fileprovider/nsfileproviderreplicatedextension). Apple actually added support for it with iOS 16.

But both these File Provider frameworks are fundamentally different. It's not like just "adding an interface", it would be a huge rewrite.

I'd love to see that as well, but unfortunately, we don't have the resources to work on such a difficult and complex task right now.
