### ISSUE TITLE
sample text editor

### ISSUE THREAD

**Issue by wittwitt** [cryptomator/ios#344]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

txt file modification is too troublesome, for complex documents such operation, no problem

### Motivation

if only edit txt file , we have to move it to my iphone disk , this is too troublesome, for complex documents such operation, no problem. if app embedded sample txt editor , this will increase frequency of use， As the main pc encryption security web disk tool, the mobile phone part is too complex, has been useless

**Comment by tobihagemann** [comment]
Thank you for your feature request. Cryptomator is fully integrated into the Files app, and we can't "embed" a text editor there. We just can hope that Apple embeds a text editor into their Files app at some point in the future.

In the meantime, I'd suggest to download a text editor of your choice. I can recommend [Subtext](https://apps.apple.com/app/subtext/id1606625287c), which seems to be the most basic plain text editor that I could find. But you can of course check out other apps that fit your needs.
