### ISSUE TITLE
Missing lock icon in vaults overwiew since update to iOS 17.4

### ISSUE THREAD

**Issue by bckntme** [cryptomator/ios#346]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Since update to iOS 17.4 the lock icon is missing in the vaults overview

### System Setup

- iOS: 17.4
- Cryptomator: 2.5.1

### Cloud Type

iCloud Drive

### Steps to Reproduce

1. Unlock vault in iOS Drive app
2. Open Cryptomator app (not from background)
3. Before iOS 17.4, when a vault was unlocked, there was an icon in the entry of the vault which could be tapped to lock the vault

### Expected Behavior

Showing lock icon

### Actual Behavior

No lock icon

### Reproducibility

Always

### Anything else?

The icon shows up when opening the details view of the unlocked vault, going back, putting Cryptomator app in background and opening again. Strange behavior.

**Comment by tobihagemann** [comment]
Thank you for reporting this issue! I'm able to reproduce this issue. Indeed, the lock icon is not visible most of the time, even though it should be. Not sure if this has anything to do with iOS 17.4, but we have to look into it.

**Comment by iammajid** [comment]
@albertojalvo, there will be a fix in the next update.
