### ISSUE TITLE
Inhalt nicht verfügbar

### ISSUE THREAD

**Issue by florianzo** [cryptomator/ios#350]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/cryptomator/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/cryptomator/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Tresor wird in der Dateien-App nicht mehr geöffnet

### What software is involved?

- Operating System: iOS 17.4 und 17.4.1
- Cryptomator: 2.5.1
- Onedrive 15.8.2

### Volume Type

None

### Steps to Reproduce

1. Dateien-App öffnen
2. Tresor entsperren
3. Fehlermeldung erscheint

### Expected Behavior

Öffnen der Tresore in der Dateien-App

### Actual Behavior

Fehlermeldung:
Inhalt nicht verfügbar
Der Ordnerinhalt konnte aufgrund eines unbekannten Fehlers nicht angezeigt werden. 

### Reproducibility

Always

### Anything else?

Mehrere Tresore sind auf onedrive gespeichert. Löschen und Neuinstallation der App hat keinen Erfolg gebracht. Ab und zu lässt sich 1 Tresor öffnen aber die anderen nicht. 

[Logs.zip](https://github.com/cryptomator/cryptomator/files/14706088/Logs.zip)

**Comment by tobihagemann** [comment]
Should be a duplicate of #345. We're looking into it!
