### ISSUE TITLE
Wrong Shortcuts Guide Link

### ISSUE THREAD

**Issue by yellowsnow3** [cryptomator/ios#354]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

When pressing the button "Shortcuts Guide" it opens a 404 documentation page, because the actual documentation moved to a different link. To fix this, the link the button opens needs to be updated.

### System Setup

- iOS: 17.4.1
- Cryptomator: 2.5.2 (1228)

### Steps to Reproduce

1. Open Cryptomator
2. Go to Settings
3. Tap on "Shortcuts Guide"

### Expected Behavior

After pressing the button, you are directed to [this page](https://docs.cryptomator.org/en/latest/ios/shortcuts-guide/).

### Actual Behavior

After pressing the button, you are directed to [this page](https://docs.cryptomator.org/en/1.6/ios/shortcuts-guide/).

### Reproducibility

Always

**Comment by tobihagemann** [comment]
Thank you for reporting this, we've fixed the "old" link for now. We'll update the links in a future update.
