### ISSUE TITLE
Edit existing file and copy new file to Vault on onedrive

### ISSUE THREAD

**Issue by Stoner60** [cryptomator/ios#358]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

If I edit a file (Excel), or copy a new file pdf to vault on OneDrive, the file is marked with a „!“ and an icon like „-„ this. I canˋt delete this file. This only happens with OneDrive, magenta or GMX Cloud works well. After remove the vault and add it new, then the error is away. The edit file is the old one and the copied file is away. Restart of iPadOS donˋt help.

### System Setup

- iOS: iPadOS 17.5.1 (21F90)
- Cryptomator: 2.5.2
- OneDrive: 15.13.2
- …

### Cloud Type

OneDrive

### Steps to Reproduce

1. Edit an Excel file with Dateien App and save this file
2. Copy a pdf to Vault on OneDrive
3. …

### Expected Behavior

An update of OneDrive isnˋt compatible to Cryptomator, or an update of iPadOS.

### Actual Behavior

![IMG_0651](https://github.com/cryptomator/ios/assets/23231213/6316bfdc-c937-4b1e-abc0-130e88268b6a)

### Reproducibility

Always

**Comment by Stoner60** [comment]
Good evening, if I copy a file to onedrive with files app, i got this issue [https://answers.microsoft.com/de-de/msoffice/forum/all/onedrive-speichert-datei-und-f%C3%BCgt-automatisch/1f6220ae-1bac-48fb-a832-2ccd69e65c7c](url). 
It seems that Cryptomator has the problems with files on onedrive, because of this issue.
I can‘t found any solutions. 

By the way, why I get no response from Cryptomator team for a few days?
Best regards Christian

**Comment by tobihagemann** [comment]
Sorry for the late response. We've fixed an issue that caused "unauthorized" errors when uploading files to OneDrive and the fix will be released in 2.6.0. The update is still being reviewed by Apple, but should hopefully soon be available in the App Store. Thank you for your patience!
