### ISSUE TITLE
"Change Password" option shown for Hub vaults

### ISSUE THREAD

**Issue by overheadhunter** [cryptomator/ios#360]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

When selecting a Hub vault, a "Change password" option is shown despite Hub not relying on passwords for key derivation

### System Setup

- iOS: 2.5.2

### Steps to Reproduce

1. Add a Hub vault
2. Select it from the main app's vault list
3. Notice there is a "Change password" option shown

### Expected Behavior

Hub vaults don't have a password

### Actual Behavior

Either omit this option or replace it with some a hyperlink "View in Browser" or something.

### Reproducibility

Always

**Comment by tobihagemann** [comment]
Fixed in #367
