### ISSUE TITLE
Cannot unlock folder after iOS 18 upgrade

### ISSUE THREAD

**Issue by linwiz** [cryptomator/ios#377]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Cannot unlock folder after iOS 18 upgrade

### System Setup

- iOS: iOS 18.0 (22A3354)
- Cryptomator: 2.6.2 (1258)

I upgraded from iOS 17 to iOS 18 and now 
I receive an error when browsing to the Cryptomator folder in the files app

Error
No valid file provider found with identifier 'com.apple.CloudDocs.i-
CloudDriveFileProvider'.

after I click ok I’m left with the following message but unlock is greyed out and I can’t do anything. 

Unlock Required
To access and show the contents of your vault, it has to be unlocked.
Unlock

### Cloud Type

iCloud Drive

### Steps to Reproduce

See above. 

### Expected Behavior

Unlock my files

### Actual Behavior

Can’t unlock my files

### Reproducibility

Always

**Comment by LinuxDonald** [comment]
I habe the same problem

**Comment by linwiz** [comment]
I fixed this by removing the vault from the app and adding it back again.  

The error message really needs to be changed to tell the user how to fix it.

**Comment by rrottmann** [comment]
Also needed to reauthenticate Cryptomator to get it working again. I removed my OneDrive account in the app and additionally deinstalled Cryptomator. When adding back the OneDrive Account and installing Cryptomator again, it asked for new authentication with the Microsoft  account. After entering the vault password, everything worked again.

**Comment by iammajid** [comment]
@LinuxDonald @linwiz Could you try reproducing the error with our latest app version? Unfortunately, I haven’t been able to replicate the issue.

**Comment by LinuxDonald** [comment]
If i disable in file Manager overview. The vaults. Cryptomator cant Open it.

**Comment by tobihagemann** [comment]
If you disable Cryptomator in the Files app, this is indeed an expected behavior that the vault can't be opened. It has to be enabled, see here: https://docs.cryptomator.org/en/latest/ios/access-vault/#enable-cryptomator-in-files-app

Doesn't sound like a bug to me?

**Comment by LinuxDonald** [comment]
But if you want to hide it?

**Comment by tobihagemann** [comment]
Unfortunately, that's not possible. We do not have any influence on the Files app itself.

**Comment by LinuxDonald** [comment]
Ah okay. Thx for the info. I don't have any other problem.
