### ISSUE TITLE
iOS 18: Vaults don't show up in Files app, if Cryptomator is hidden

### ISSUE THREAD

**Issue by jbrepogmailcom** [cryptomator/ios#379]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

When openning (dropbox) trezor, I have nothing listed in list of servers that I can connect to

### System Setup

- iOS: 18
- Cryptomator: 2.6.2
- …

### Cloud Type

Dropbox

### Steps to Reproduce

1. Click "Show in files"
2. Click "Attach server"
3. ...nothing. I expect Cryptomator server (or Dropbox)? Instead, I only get editable field to fill in server address

### Expected Behavior

Either I see Cryptomator or Dropbox in list of servers that can be attached

### Actual Behavior

I only get editable field to fill in server address

### Reproducibility

Always

**Comment by jbrepogmailcom** [comment]
I discovered why is that. When Cryptomator is "hidden app", which is a new feature of iOS 18, it is also invisible for Files and cannot be added there. It only works when Cryptomator is normal visible application

**Comment by overheadhunter** [comment]
Thanks for reporting, seems like this is behavior is intended by Apple.
