### ISSUE TITLE
Cannot open symbolic link correctly.

### ISSUE THREAD

**Issue by snyhai** [cryptomator/ios#395]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Cannot open symbolic link correctly. Make by command ln

### System Setup

- iOS: iOS 18.1 (22B83)
- Cryptomator: 2.6.3(1273)
- …

### Steps to Reproduce

Cannot open symbolic link correctly. Make by command ln

### Expected Behavior

 open symbolic link correctly.

### Actual Behavior

Cannot open symbolic link correctly. Make by command ln

### Reproducibility

Always

**Comment by tobihagemann** [comment]
@snyhai Can you be more specific? This doesn't sound like an issue with iOS. Maybe you meant to post this in a different repository? In fact, you're right that symbolic links don't work on iOS, but what are the steps to reproduce? What is the expected behavior? You didn't really fill out the form.

**Comment by snyhai** [comment]
```log
❯ ll -aR
total 607030707
drwxr-xr-x  1 snyhai  staff   160B Nov  6 17:05 .
drwxr-xr-x  1 snyhai  staff   256B Nov  6 17:03 ..
lrw-r--r--  1 snyhai  staff     8B Nov  6 17:05 source -> ./target
drwxr-xr-x  1 snyhai  staff   128B Nov  6 17:03 target

./target:
total 2
drwxr-xr-x  1 snyhai  staff   128B Nov  6 17:03 .
drwxr-xr-x  1 snyhai  staff   160B Nov  6 17:05 ..
-rw-r--r--  1 snyhai  staff     0B Nov  6 17:03 testfile
```
that work perfectly on my mac
while open in ios, `source` can be identified as directory, however while open `source`, it will keep loading.
I know ios doesn't natively support symlinks, is this possible to fix.

**Comment by snyhai** [comment]
![IMG_2AB43FA77F26-1](https://github.com/user-attachments/assets/82f3cbd0-624d-4ed3-949d-0c7f33559762)
![IMG_2AB43FA77F26-2](https://github.com/user-attachments/assets/b58cdf52-e43d-4182-b910-1201ebbac196)
Looks like this
