### ISSUE TITLE
Unable to add vault due to "callerBundleId" error

### ISSUE THREAD

**Issue by jmreekes** [cryptomator/ios#43]

**Comment by tobihagemann** [comment]
I think it's worth re-opening this issue because we've seen similar reports with the "callerBundleId" error. Indeed, the workaround "restart device" seems to be working in all cases but that's not the user experience that we'd like to achieve. :smile:

**Comment by tobihagemann** [comment]
If I'm not mistaken, this actually never happened in the App Store version and was/is exclusive to TestFlight.
