### ISSUE TITLE
Cryptomator 2 Beta

### ISSUE THREAD

**Issue by Quorum75** [cryptomator/ios#49]
It is impossible to add an existing Vault. 

For instance when trying to add Dropbox Vault I get a pop error after validing the password. 

![image](https://user-images.githubusercontent.com/49731083/124269618-6476e900-db3b-11eb-8229-b8a16082ef6e.png)

**Comment by tobihagemann** [comment]
Duplicate of #43

We really don't know what could cause this but restarting the device helps for now.

**Comment by Quorum75** [comment]
OK it worked.
