### ISSUE TITLE
Vaults in OneDrive are not added to the vault list

### ISSUE THREAD

**Issue by Quorum75** [cryptomator/ios#50]
It can login to Onedrive vaults but it doesn't add the vault to the vaults list. 

<img src="https://user-images.githubusercontent.com/49731083/124389756-e8ba9f00-dce8-11eb-8b97-d904337f6efe.png" width="414">

If I need to access Onedrive I need to follow the process "Open Existing Vault" everytime.

**Comment by tobihagemann** [comment]
I'm unable to reproduce the issue. Could you please give more details? See [bug report template](https://github.com/cryptomator/ios/blob/develop/.github/ISSUE_TEMPLATE/bug.md) for guidance.

And also: If you'd like to report more issues regarding the new app in the future, please create them in this repository and not in [cryptomator/cryptomator-ios](https://github.com/cryptomator/cryptomator-ios), thank you!

**Comment by Quorum75** [comment]
OK will do. 

FYI I deleted the app and installed it again. For no reasons, Onedrive now appears in the list 👍🏻

I don't know what went wrong but now it works fine.  So issue closed.
