### ISSUE TITLE
Some filetypes are greyed out

### ISSUE THREAD

**Issue by StanoRiga** [cryptomator/ios#67]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Some files are greyed out and not accessible/movable

### System Setup

- iOS: 2.0.0 (471)

### Cloud Type

Google Drive, WebDAV

### Steps to Reproduce

1. store a "*.msg" or a *.contact" file in your vault (tested with google drive and own webdav storage)
2. perform sync with online storage
3. open iOS cryptomator and navigate to the file
4. file is greyed out, you can not select it or do anything with it

### Expected Behavior

no files are greyed out, at least every file should be able to be shared/copied from inside the vault to other programs or storage path

### Actual Behavior

files are greyed out, it is not possible to select or move or copy or access them.

### Reproducibility

Always

### Anything else?

Screenshots:
![IMG_5458](https://user-images.githubusercontent.com/30843029/127107931-ce9f2c16-d352-48fb-a450-27451eebd26f.jpg)
![IMG_5459](https://user-images.githubusercontent.com/30843029/127107934-93c50a56-a8ec-456a-89d5-6dbf7bd3a2f0.jpg)
![IMG_5460](https://user-images.githubusercontent.com/30843029/127107936-f06ed404-c2be-4d40-935d-875d36a60a2f.jpg)

**Comment by phil1995** [comment]
Thanks for reporting this issue!
It seems that for unknown filetypes we returned a dynamically created UTI, which the Files App could not handle. Therefore, we now check if we would return a dynamically created UTI and return a generic UTI (`kUTTypeData`) instead. This makes it possible to perform operations on unknown file types in the Files app.
