### ISSUE TITLE
Vaults disappear after update

### ISSUE THREAD

**Issue by Quorum75** [cryptomator/ios#77]
### Description

When trying to upload multiple files from iCloud to Cryptomator 2 Onedrive Vault only one file is uploaded.  

### System Setup

* Operating system and version: iPhone 11Pro Max.on iOS 14.7
* Cryptomator version: 2.0.0 (502)
* Volume type: [Dokany/FUSE/WebDAV, shown in the settings] All Cloud srrvices

### Steps to Reproduce

Open Cryptomator after the app update and you will see that all vaults are not present anymore. 
#### Expected Behavior

Keep the vaults that have been added to the Cryptomator app. 

#### Actual Behavior

After each update of Cryptomator application all my Vaults disappear and I have to add them again. . 

#### Reproducibility

Always. 

### Additional Information

**Comment by tobihagemann** [comment]
Thank you for your bug report. However, I'd like to remind you again to post issues regarding Cryptomator 2.0 to _this_ repository (`cryptomator/ios` and not `cryptomator/cryptomator-ios`).

I'm not sure how to categorize this issue but it's not really a "bug" even though it might look like one.

This behavior is documented in the release notes:

> Be aware that with this update, you have to set up your vaults again. This will happen during the beta from time to time, probably more often in the beginning. Sorry for the inconvenience that this may cause.

It might be annoying but we'd like to keep it simple during this early beta. Will of course be different in the final release.

**Comment by Quorum75** [comment]
Sorry, updates being done automatically in the background I don't check all the time the release notes. 

About the repo, I can't post in the one you are mentioning because it does not offer any option for it. 
![image](https://user-images.githubusercontent.com/49731083/129303279-5f0c0c9e-4bcf-46cb-abe5-524e62449827.png)

**Comment by tobihagemann** [comment]
Not sure what you mean but it _is_ an expected behavior (hence the remark in the release notes). But _only_ during the beta, of course.

Ohhh, I didn't know that the new [issue forms (beta)](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms) don't work in the mobile apps. If possible, please create a new issue with a web browser.

**Comment by Quorum75** [comment]
"Ohhh, I didn't know that the new issue forms (beta) don't work in the mobile apps. If possible, please create a new issue with a web browser."

It does work but I guess you didn't set it up correctly. There is no issue on others rep.
