### ISSUE TITLE
Unable to open vault on iOS 15

### ISSUE THREAD

**Issue by m4rkv5** [cryptomator/ios#81]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

The Vault can't be opened via Files app since 502. Version 2.0.0 (471) is working.

### System Setup

- iOS: 15 Public Beta 5/6
- Cryptomator: 2.0.0 (502/516)
- iPhone 11 Pro

### Cloud Type

iCloud Drive, WebDAV

### Steps to Reproduce

1. Vault added via WebDAV or Other File Provider iCloud
2. Open Files App
3. Select Vault
4. Dialog Authentication necessary 
5. Press authenticate
6. Cryptomator popup opens "Welcome..." the only option is to Open Cryptomator
7. Opening Cryptomator App
8. Nothing happens
9. Installing Cryptomator: 2.0.0 (471)
10. Repeating Step 1-3
11. Files can be viewed

Video: https://www.icloud.com/photos/#03h1b_ASTLgmWJ18H5PlITcig

### Expected Behavior

Accessible Files

### Actual Behavior

Nothing happens

### Reproducibility

Always

### Relevant Log Output

```shell
2021/08/18 16:06:05:049  FPExt: persistentIdentifierForItem(at: file:///private/var/mobile/Containers/Shared/AppGroup/240AE038-D3E0-45CF-BAEE-E0C75C47A3C9/File%20Provider%20Storage/BB9273B0-E591-4404-9E15-7A23E1FE7C43/) called
2021/08/18 16:06:05:049  FPExt: item(for: NSFileProviderItemIdentifier(_rawValue: File Provider Storage)) called
2021/08/18 16:06:05:051  FPExt: persistentIdentifierForItem(at: file:///private/var/mobile/Containers/Shared/AppGroup/240AE038-D3E0-45CF-BAEE-E0C75C47A3C9/File%20Provider%20Storage/BB9273B0-E591-4404-9E15-7A23E1FE7C43/) called
2021/08/18 16:06:05:051  FPExt: item(for: NSFileProviderItemIdentifier(_rawValue: File Provider Storage)) called
2021/08/18 16:06:05:053  FPExt: urlForItem(withPersistentIdentifier: NSFileProviderItemIdentifier(_rawValue: NSFileProviderRootContainerItemIdentifier)) called
2021/08/18 16:06:05:053  FPExt: item(for: NSFileProviderItemIdentifier(_rawValue: NSFileProviderRootContainerItemIdentifier)) called
2021/08/18 16:06:05:460  FPExt: enumerator(for: NSFileProviderItemIdentifier(_rawValue: NSFileProviderRootContainerItemIdentifier)) called
2021/08/18 16:06:05:460  FPExt: item(for: NSFileProviderItemIdentifier(_rawValue: NSFileProviderRootContainerItemIdentifier)) called
2021/08/18 16:06:05:462  enumerateItems called for identifier: NSFileProviderItemIdentifier(_rawValue: NSFileProviderRootContainerItemIdentifier)
2021/08/18 16:06:05:463  enumerateItems getAdapter failed with: passwordNotFound for identifier: NSFileProviderItemIdentifier(_rawValue: NSFileProviderRootContainerItemIdentifier)
```

### Anything else?
Found something similiar on reddit: 
https://reddit.com/r/Cryptomator/comments/p1udpo/unable_to_authenticate/

**Comment by tobihagemann** [comment]
I'm pretty sure that this issue appears exclusively on iOS 15. We'll look into it.

**Comment by m4rkv5** [comment]
@tobihagemann Unter iOS 15 funktioniert der Passwort unlock nun mit der neusten Version. Danke!
