### ISSUE TITLE
Can't connect to Infomaniak

### ISSUE THREAD

**Issue by Quorum75** [cryptomator/ios#82]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

connection to Infomaniak WebDAV doesn't work

### System Setup

Operating system and version: iPhone 11Pro Max.on iOS 14.7
Cryptomator version: 2.0.0 (516)
Volume type: WebDAV

### Cloud Type

WebDAV

### Steps to Reproduce

1. Click on + and Create New Vault
2. Type à Vault name
3. Choose WebDAV 
4. Click + 
5. Type https://connect.drive.infomaniak.com/
6. Type user name and password

### Expected Behavior

Get connected to Infomaniak in order to create a vault. 

### Actual Behavior

[Error message screen shot](https://ibb.co/fC65B3D)

### Reproducibility

Always

### Anything else?

Because 2FA is activated in Infomaniak, an application password has been activated following Infomaniak [support page](https://www.infomaniak.com/en/support/faq/2409/kdrive-logging-in-to-your-drive-via-webdav )

**Comment by tobihagemann** [comment]
Admittedly, the error message could be better. Well, that's a bummer, I think we didn't improve our logging in the last version enough. It could mean anything at this point, even something benign as "wrong credentials". I'll improve some error messages and logging with the next version.

**Comment by tobihagemann** [comment]
Could you please try again with the latest version? Thank you!

**Comment by Quorum75** [comment]
Hi. Sorry still not working. 

![image](https://user-images.githubusercontent.com/49731083/130246043-0ff56060-7668-4c7b-9e5a-ec589ec32ff4.jpeg)

**Comment by tobihagemann** [comment]
Okay, that's [HTTP response status code 403](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403), which means: Username/password is correct (otherwise, you would get a different error message with [HTTP response status code 401](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401)) but the access if "forbidden".

Does it work with a different WebDAV client? https://www.infomaniak.com/en/support/faq/2409/kdrive-logging-in-to-your-drive-via-webdav

Also interesting:

> This access option is only available for paid kDrive services.

**Comment by Quorum75** [comment]
_This access option is only available for paid kDrive services._

That would be the reason as I only pay for pcloud. KDrive is on testing only at the present time. 

Mystery solved! 😁
