### ISSUE TITLE
Loss of iCloud pathname (?)

### ISSUE THREAD

**Issue by p4nggi** [cryptomator/ios#85]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Vaults created in macOS do not appear in iOS

### System Setup

- iOS: 14.7.1
- Cryptomator: 2.0.0(529)
- macOS:11.5.2
- Cryptomator: SNAPSHOT (dmg-3205) (1.6.0 beta 1 release)
- (macFUSE 4.1.2)

### Cloud Type

iCloud Drive

### Steps to Reproduce

1. When I create a vault in Mac os and specify a path, I choose the 'iCloud Drive' option, not a custom location.
The path names that appeared were as follows.

`~/Library/Mobile Documents/iCloud~com~setolabs~Cryptomator/Documents/(vault name)`

/*
When I selected a vault store location directly on the iCloud through a custom path, it was as follows.

`~/Library/Mobile Documents/com~apple~CloudDocs/(vault name)`
*/
2. Saved vaults did not appear in iOS. Both File App and Cryptomator App

### Expected Behavior

The stored vaults are shown as normal.

### Actual Behavior

Does not appear.

### Reproducibility

Always

### Relevant Log Output

```shell
-
```

### Anything else?

I think it's just a question of whether iOS can call up the path name or not, and it's normal if I direct the file location to the iCloud.

Also, I could see that cryptomater storage, which was not shown in the file app and cryptomater app, appears through cloud storage management in the iOS setup app.

When I choose a storage in a mac environment, there is no problem if I specify it myself, but is there another way that is not like this?

**Comment by p4nggi** [comment]
I'm not talking about making a vault on an **iPhone.**
The problem occurs on the iPhone, but should I move the issue to Mac version cryptomator?

--
When I create a vault in the path
`~/Library/MobileDocuments/iCloud~com~setolabs~Cryptomater/Documents/<vault-name>`
in **MAC**, the vault _does not display_ in the iPhone Explorer. Even though it definitely exists.

If I designate the iCloud as a storage through the Finder in Mac, there is no problem.
path:
`~/Library/Mobile Documents/com~apple~CloudDocs/<vault-name>`
--
Is it a problem related to the name of the container package?

**Comment by tobihagemann** [comment]
Oh, I probably misunderstood your issue. No, it has nothing to do with the path names.

If you're looking for the vault located inside `iCloud~com~setolabs~Cryptomator` on iOS, you can find it under "iCloud Drive > Cryptomator".

**Comment by p4nggi** [comment]
Yes it is invisible to me. ...
<img width="378" alt="screenshot-mac" src="https://user-images.githubusercontent.com/89845846/131703032-6c22db4e-e8f6-41cf-9a54-aa6be29ee1d7.png">
1. 'iCloud~com~setolabs~cryptomator' automatically specified by the Cryptomator Mac app.
Appeared.
2. My own created Cryptomator folder appears

But
![screenshot-iphone](https://user-images.githubusercontent.com/89845846/131703391-63276190-c045-4652-8737-dac79db258cb.PNG)
![screenshot-iphone2](https://user-images.githubusercontent.com/89845846/131703402-2b69e5ef-8587-4f4c-a7f4-a8f2b1f3a626.PNG)
Only my own created Cryptomator folder appears

Synchronization is complete, and storage optimization is off.

**Comment by tobihagemann** [comment]
If you go to https://www.icloud.com/iclouddrive/, is the "special" Cryptomator folder (with icon) visible there?

**Comment by p4nggi** [comment]
Yes, it is visible.
<img width="558" alt="스크린샷 2021-09-02 오전 1 16 17" src="https://user-images.githubusercontent.com/89845846/131706958-65f5bb45-e089-4458-a6a9-6d4c8cef1fb1.png">

**Comment by p4nggi** [comment]
I just installed and ran the App Store version cryptomater to solve the problem, and a folder that was invisible on the iCloud suddenly appeared.

I think the special cryptomator folder with the icon is linked to the app store version.

But it doesn't seem to be linked to the iOS beta cryptomator.

What do you think of this?
I've installed the App Store version before, so I'm not sure if it's a temporary conflict or a problem with the beta version program.

Anyway, it's working fine now.

Thank you for your help.

+
In addition, if the name of the file I save in my vault contains Korean, the app store version Cryptomator actually uploads successfully, but the upload stops and the screen looks frozen.

**Comment by p4nggi** [comment]
And as a way to solve the problem,
I've tried all the ways to turn off and turn on my iCloud drive, re-log in to my Apple account, or reboot my device.

**Comment by p4nggi** [comment]
The special Cryptomator folder that reappears after installing the App Store version can still be seen in the file app even if the old app is erased again.

But I think this can still cause confusion for the user.

Thank you for opening up the right issue.
