### ISSUE TITLE
OneDrive - Can't save file

### ISSUE THREAD

**Issue by Quorum75** [cryptomator/ios#97]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

OneDrive - Can't save file

### System Setup

- Operating system and version: iPhone 13 Pro Max.on iOS 15.1
- Cryptomator version: 2.0.0 (575)
- Volume type: Cloud/OneDrive 

### Cloud Type

OneDrive

### Steps to Reproduce

1. Select a PDF file from a website
2. Use iOS Sharesheet
3. Select Save Files
4. Choose OneDrive Cryptomator
5. Click Save
6. Error message "The operation cannot be completed. No such file or directory"

### Expected Behavior

Be able to save the file in the chosen directory.

### Actual Behavior

Response from the system that the directory does not exist when actually it exists and has been chosen as the directory to save the file.

![Error Message](https://user-images.githubusercontent.com/49731083/139470942-7e7c63e0-3c07-43e3-a781-19f6cad469f0.jpg)

### Reproducibility

Often

**Comment by tobihagemann** [comment]
I'm unable to reproduce this issue. The steps are eerily similar to #98. Is there anything specific about this folder? Could you please enable "Debug Mode" in the Cryptomator settings, reproduce the issue, and then use "Send Log File" to export the logs? Don't forget to disable debug mode after that. Thank you!

**Comment by Quorum75** [comment]
It is similar but the outcome is different. It doesn't happen everytime but sometime. I will send you the log and will notify you here when it happens again.

**Comment by Quorum75** [comment]
I think I know what the problem is about. It is a syntax issue. So the pop error window isn't correct and brings confusion on the error type.
