### ISSUE TITLE
Can't save and replace an existing file

### ISSUE THREAD

**Issue by Quorum75** [cryptomator/ios#98]
### Please agree to the following

- [X] I have searched [existing issues](https://github.com/cryptomator/ios/issues?q=) for duplicates
- [X] I agree to follow this project's [Code of Conduct](https://github.com/cryptomator/ios/blob/develop/.github/CODE_OF_CONDUCT.md)

### Summary

Can't save and replace an existing file

### System Setup

- Operating system and version: iPhone 13 Pro Max.on iOS 15.1
- Cryptomator version: 2.0.0 (575)
- Volume type: Cloud/OneDrive 

### Cloud Type

OneDrive

### Steps to Reproduce

1. Save any file in OneDrive Cryptomator foder.
2. Try to save again the file in the same directory.
3. You get a message asking if you want to replace the file.
4. Choose "Replace"
5. You get another message saying you can't replace the file.
6. Try to save it again (Step 2)
7. The save is correctly saved.

### Expected Behavior

Be able to save and replace an existing file.

### Actual Behavior

Can't save and replace the file on the first try. Must do it a second time.

![Replace File Message](https://user-images.githubusercontent.com/49731083/139471752-f7ecc40e-fb85-4067-8e19-6c24175e1664.jpg)

![Cannot copy file message](https://user-images.githubusercontent.com/49731083/139471758-b7843056-8b21-4e15-98e0-d2b8b8ab739c.jpg)

### Reproducibility

Always

### Anything else?

It would be great if you could activate the Bug report access on Github iOS app.

**Comment by tobihagemann** [comment]
I can reproduce the issue. It doesn't seem to be OneDrive-specific. I noticed something even worse: After the "already exists in the location", the file disappears completely.

**Comment by Quorum75** [comment]
Wow! Indeed very scaring. I checked again but on my side, hopefully, I don't have this issue.
